// Dashboard bilingual support — English / Arabic
(function () {

  var T = {
    en: {
      // Sidebar — Sales System
      nav_sales_system:   'Sales System',
      nav_sales_overview: 'Sales Overview',
      nav_leads:          'Leads & Opportunities',
      nav_quotes_bookings:'Quotes & Booking Requests',
      nav_sales_forms:    'Sales Forms',
      nav_calendar:       'Calendar Management',
      nav_tasks:          'Tasks & Follow-Ups',
      nav_reports:        'Reports & Analytics',
      nav_approvals:      'Approvals & Audit',
      // Shared sales vocabulary
      product_concrete:   'Concrete',
      product_precast:    'Precast',
      product_block:      'Construction Block',
      priority_high:      'High',
      priority_medium:    'Medium',
      priority_low:       'Low',
      stage_new:          'New',
      stage_contacted:    'Contacted',
      stage_qualified:    'Qualified',
      stage_quoted:       'Quoted',
      stage_negotiation:  'Negotiation',
      stage_won:          'Won',
      stage_lost:         'Lost',
      src_walkin:         'Walk-in',
      src_phone:          'Phone',
      src_website:        'Website',
      src_rep:            'Representative',
      lbl_follow_up:      'Follow-up Date',
      lbl_priority:       'Priority',
      lbl_stage:          'Stage',
      lbl_product_type:   'Product Type',
      lbl_source:         'Lead Source',
      lbl_rep:            'Representative',
      status_booked:      'Booked',
      status_paid:        'Paid',
      status_delayed:     'Delayed',
      status_cancelled:   'Cancelled',
      status_expired:     'Expired',
      status_pending_conf:'Pending Confirmation',
      btn_add:            'Add',
      btn_save:           'Save',
      btn_cancel:         'Cancel',
      btn_delete:         'Delete',
      btn_edit:           'Edit',
      btn_close:          'Close',
      // Leads page
      page_leads:         'Lead & Opportunity Management',
      btn_add_lead:       'Add Lead →',
      leads_all:          'All',
      lbl_name:           'Name',
      lbl_company:        'Company',
      lbl_notes:          'Notes',
      th_waiting:         'Waiting',
      th_follow_up:       'Follow-up',
      th_product:         'Product',
      th_actions:         'Actions',
      leads_overdue_fu:   'Overdue',
      leads_dup_warn:     'Possible duplicate — matching records found:',
      leads_none:         'No leads yet',
      leads_none_d:       'Add your first lead to start tracking the sales pipeline.',
      btn_convert:        'Convert to Quote',
      leads_converted:    'Converted',
      modal_add_lead:     'Add Lead',
      modal_edit_lead:    'Edit Lead',
      fu_required:        'A follow-up date is required before saving.',
      name_required:      'Name and phone are required.',
      toast_lead_saved:   'Lead saved',
      toast_lead_deleted: 'Lead deleted',
      toast_lead_converted:'Lead converted to a quote request',
      del_lead_t:         'Delete Lead',
      del_lead_d:         'This permanently removes the lead. This cannot be undone.',
      ph_search_leads:    'Search leads…',
      ph_rep_name:        'Representative name…',
      ph_lead_notes:      'Notes about this lead…',
      // Sales Forms page
      page_sales_forms:   'Sales Forms',
      sf_intro:           'Create a quote or booking on behalf of a client — walk-in, phone, or representative requests.',
      sf_tab_concrete:    'Concrete Booking',
      sf_tab_precast:     'Precast Quote',
      sf_tab_block:       'Construction Block Quote',
      sf_client:          'Client Name',
      sf_location:        'Project Location',
      sf_qty_m3:          'Quantity (m³)',
      sf_qty_units:       'Quantity (units)',
      sf_qty_pcs:         'Quantity (pieces)',
      sf_req_date:        'Required Date',
      sf_dispatch:        'Dispatch Time Frame',
      sf_mix_grade:       'Mix Grade',
      sf_precast_product: 'Precast Product',
      sf_block_product:   'Block Product',
      sf_details:         'Additional Details',
      sf_add_customer:    'Add this client to the Customer Database',
      sf_existing_customer:'Matched an existing customer record — no duplicate will be created.',
      sf_submit:          'Create & Send to Workflow →',
      sf_required_err:    'Please fill all required fields.',
      sf_success:         'Created successfully — now in Quotes & Booking Requests',
      sf_view_req:        'View Requests →',
      sf_approval_note:   'This request will require approval:',
      apr_large_volume:   'Large volume booking',
      apr_high_discount:  'Discount above threshold',
      apr_same_day:       'Urgent same-day dispatch',
      sf_dw_morning:      'Morning (06:00–10:00)',
      sf_dw_midday:       'Midday (10:00–14:00)',
      sf_dw_afternoon:    'Afternoon (14:00–18:00)',
      sf_dw_evening:      'Evening (18:00–22:00)',
      sf_dw_flexible:     'Flexible',
      pc_hollow:          'Hollow-core Slabs',
      pc_wall:            'Wall Panels',
      pc_beam:            'Beams & Columns',
      pc_stairs:          'Stairs',
      pc_boundary:        'Boundary Walls',
      pc_custom:          'Custom Element',
      bl_nh20:            'Normal Hollow Block (20cm)',
      bl_ns20:            'Normal Solid Block (20cm)',
      bl_ins20:           'Insulated Block (20cm)',
      bl_ins30:           'Blue Insulated Block (30cm)',
      bl_wins30:          'White Insulated Block (30cm)',
      // Calendar page
      page_calendar:      'Calendar Management',
      cal_add_entry:      'Add Entry →',
      cal_export:         'Export',
      cal_export_day:     'Today (CSV)',
      cal_export_week:    'This Week (CSV)',
      cal_export_month:   'This Month (CSV)',
      cal_today:          'Today',
      cal_unassigned:     'Unassigned Queue',
      cal_unassigned_d:   'Requests without a delivery date or dispatch window.',
      cal_schedule:       'Schedule',
      cal_capacity:       'Daily capacity',
      cal_conflict_window:'Dispatch window overlap',
      cal_conflict_capacity:'Daily capacity exceeded',
      cal_tentative:      'Tentative',
      cal_upcoming:       'Upcoming (next 3 days)',
      cal_none_upcoming:  'Nothing scheduled in the next 3 days.',
      cal_entry:          'Calendar Entry',
      cal_day:            'Day',
      cal_qty:            'Quantity',
      cal_mark_tentative: 'Tentative booking (reserve space before confirmation)',
      cal_filter_region:  'Filter by location…',
      cal_filter_rep:     'Filter by representative…',
      cal_empty_day:      'No entries',
      toast_entry_saved:  'Calendar entry saved',
      toast_entry_deleted:'Calendar entry deleted',
      toast_rescheduled:  'Rescheduled',
      cal_linked_req:     'Linked request',
      // Customer profile
      cust_profile:       'Customer Profile',
      cust_timeline:      'Activity Timeline',
      cust_key:           'Key Account',
      cust_mark_key:      'Mark as key account (important repeat customer)',
      lbl_segment:        'Segment',
      seg_none:           '— None —',
      seg_contractor:     'Contractor',
      seg_consultant:     'Consultant',
      seg_walkin:         'Walk-in',
      seg_government:     'Government',
      seg_retail:         'Retail',
      seg_developer:      'Developer',
      cust_stats:         'Sales History',
      cust_quotes_n:      'Quotes',
      cust_booked_n:      'Booked / Paid',
      cust_volume_n:      'Total Volume',
      cust_no_timeline:   'No activity recorded yet.',
      toast_cust_saved:   'Customer saved',
      flt_all_segments:   'All Segments',
      // Tasks page
      page_tasks:         'Tasks & Follow-Ups',
      btn_add_task:       'Add Task →',
      task_all:           'All',
      task_open:          'Open',
      task_overdue:       'Overdue',
      task_done:          'Done',
      task_title:         'Task',
      task_due:           'Due Date',
      task_assignee:      'Assigned To',
      task_link:          'Related Record',
      task_link_none:     '— Not linked —',
      task_link_request:  'Quote / Booking',
      task_link_lead:     'Lead',
      task_link_customer: 'Customer',
      task_none:          'No tasks yet',
      task_none_d:        'Create follow-up tasks so nothing slips through the cracks.',
      task_mark_done:     'Mark done',
      task_reopen:        'Reopen',
      modal_add_task:     'Add Task',
      modal_edit_task:    'Edit Task',
      task_title_req:     'A task title and due date are required.',
      toast_task_saved:   'Task saved',
      toast_task_deleted: 'Task deleted',
      ph_task_title:      'e.g. Call client about the C35 quote…',
      ph_search_tasks:    'Search tasks…',
      // Sidebar
      nav_overview:       'Overview',
      nav_bookings:       'Quotes & Booking Requests',
      nav_inbox:          'Inbox',
      nav_profile:        'Company Profile',
      nav_upload_profile: 'Upload PDF',
      profile_no_upload:  'No profile uploaded yet',
      profile_updated:    'Company profile updated successfully!',
      nav_customers:      'Customer Database',
      nav_access:         'User Access',
      nav_settings:       'Settings',
      nav_role:           'System Manager',
      nav_back:           'Back to Website',
      nav_logout:         'Logout',
      // Overview
      page_overview:      'Sales Overview',
      kpi_requests:       'Total Requests',
      kpi_leads:          'New Leads',
      kpi_volume:         'Est. Volume (m³)',
      kpi_quotes:         'Active Quotes',
      recent_title:       'Recent Quote Requests',
      recent_view_all:    'View All →',
      th_client_name:     'Client Name',
      th_date:            'Date Submitted',
      th_qty_m3:          'Quantity (m³)',
      th_status:          'Status',
      // Status badges
      status_pending_r:   'Pending Review',
      status_pending:     'Pending',
      status_quote_sent:  'Quote Sent',
      status_approved:    'Approved',
      status_contacted:   'Contacted',
      status_rejected:    'Rejected',
      // Bookings
      page_bookings:      'Quotes & Booking Requests',
      btn_filter:         'Filter',
      filter_by_status:   'Filter by Status',
      filter_all:         'All Requests',
      filter_clear:       'Clear filters',
      label_quantity:     'Quantity',
      label_mix:          'Mix Type',
      label_location:     'Location',
      label_client_msg:   'Client Message',
      label_client:       'Client',
      btn_gen_quote:      'Generate Quote →',
      btn_upd_status:     'Update Status',
      // Quote modal
      modal_gen_quote:    'Generate Quote',
      modal_client:       'Client',
      modal_qty:          'Quantity',
      modal_mix:          'Mix Type',
      modal_price:        'Price per m³ (SAR)',
      modal_total:        'Total (SAR)',
      modal_delivery:     'Delivery Date',
      modal_notes:        'Notes to Client',
      modal_cancel:       'Cancel',
      modal_send_quote:   'Send Quote',
      toast_quote_sent:   'Quote sent successfully!',
      modal_discount:     'Discount (%)',
      modal_expiry:       'Quote Expiry',
      modal_reason:       'Reason for Change',
      ph_reason:          'Why is this quote being revised?',
      apr_submitted:      'Quote saved and submitted for approval. The client email will be sent after approval.',
      apr_pending_banner: 'Awaiting approval — client email is on hold.',
      apr_rejected_banner:'Approval rejected.',
      exp_expires:        'Expires',
      flt_all_products:   'All Products',
      // Status modal
      modal_upd_status:   'Update Status',
      modal_new_status:   'New Status',
      modal_int_note:     'Internal Note (optional)',
      modal_save_status:  'Save Status',
      toast_status_saved: 'Status updated successfully!',
      // Inbox
      page_inbox:         'Inbox',
      tab_all:            'All',
      tab_unread:         'Unread',
      tab_flagged:        'Flagged',
      btn_send_reply:     'Send Reply',
      // Customers
      page_customers:     'Customer Database',
      btn_export:         'Export CSV',
      btn_add_record:     'Add Record →',
      btn_sort:           'Sort',
      th_cust_name:       'Customer Name',
      th_email:           'Email',
      th_phone:           'Phone',
      th_last_activity:   'Last Activity',
      th_location_c:      'Location',
      action_view:        'View Details →',
      pagination_cust:    'Showing 1 to 4 of 97 results',
      // Access
      page_access:        'Access Management',
      btn_add_user:       'Add User →',
      active_personnel:   'Active Personnel',
      th_name:            'Name',
      th_role_a:          'Role',
      th_status_a:        'Status',
      status_active:      'Active',
      status_inactive:    'Inactive',
      action_manage:      'Manage',
      pagination_access:  'Showing 1 to 3 of 12 personnel',
      module_access:      'Module Access Control',
      access_bookings:    'Quote Requests',
      access_bookings_d:  'View and manage bookings',
      access_financials:  'Financials',
      access_fin_d:       'Access financial reports',
      access_customers:   'Customer Data',
      access_cust_d:      'View customer database',
      access_settings:    'System Settings',
      access_sett_d:      'Modify system configuration',
      btn_save_config:    'Save Configuration',
      btn_revoke:         'Revoke All Access',
      // Settings
      page_settings:      'Settings',
      btn_save_changes:   'Save Changes',
      toast_saved:        'Settings saved successfully',
      sect_company:       'Company Information',
      lbl_co_name:        'Company Name',
      lbl_website:        'Website URL',
      lbl_co_email:       'Contact Email',
      lbl_co_phone:       'Phone Number',
      lbl_address:        'Head Office Address',
      sect_account:       'Account & Password',
      lbl_username:       'Admin Username',
      lbl_cur_pass:       'Current Password',
      lbl_new_pass:       'New Password',
      lbl_confirm_pass:   'Confirm New Password',
      sect_notif:         'Notification Preferences',
      notif1_t:           'New Booking Request',
      notif1_d:           'Get notified when a new concrete booking is submitted',
      notif2_t:           'New Inbox Message',
      notif2_d:           'Get notified when a customer submits a contact form',
      notif3_t:           'New Customer Record',
      notif3_d:           'Alert when a new customer is added to the database',
      notif4_t:           'Weekly Summary Report',
      notif4_d:           'Receive a weekly digest of requests, leads, and volumes',
      sect_system:        'System Preferences',
      lbl_lang:           'Default Language',
      lbl_tz:             'Timezone',
      lbl_date_fmt:       'Date Format',
      lbl_vol_unit:       'Volume Unit',
      sect_danger:        'Danger Zone',
      danger_t:           'Clear All Booking Records',
      danger_d:           'Permanently delete all booking requests from the system. This cannot be undone.',
      btn_clear:          'Clear Records',
      // Login
      login_heading:      'ACCESS',
      login_sub:          'Authorized personnel only',
      lbl_username_l:     'Username / Email',
      lbl_password:       'Password',
      forgot_pw:          'Forgot password?',
      btn_login:          'LOGIN →',
      login_footer:       'Secure System Environment',
      // Placeholders
      ph_search:          'Search…',
      ph_search_req:      'Search requests…',
      ph_search_cust:     'Search customers…',
      ph_search_pers:     'Search personnel…',
      ph_username:        'Enter your username or email',
      ph_password:        'Enter your password',
      ph_reply:           'Write a reply…',
      ph_int_note:        'Add an internal note about this status change…',
      ph_notes:           'Add any delivery notes, conditions, or instructions…',
    },

    ar: {
      // Sidebar — Sales System
      nav_sales_system:   'نظام المبيعات',
      nav_sales_overview: 'نظرة عامة على المبيعات',
      nav_leads:          'العملاء المحتملون والفرص',
      nav_quotes_bookings:'عروض الأسعار وطلبات الحجز',
      nav_sales_forms:    'نماذج المبيعات',
      nav_calendar:       'إدارة التقويم',
      nav_tasks:          'المهام والمتابعات',
      nav_reports:        'التقارير والتحليلات',
      nav_approvals:      'الموافقات والتدقيق',
      // Shared sales vocabulary
      product_concrete:   'خرسانة',
      product_precast:    'مسبقة الصب',
      product_block:      'بلوك بناء',
      priority_high:      'عالية',
      priority_medium:    'متوسطة',
      priority_low:       'منخفضة',
      stage_new:          'جديد',
      stage_contacted:    'تم التواصل',
      stage_qualified:    'مؤهل',
      stage_quoted:       'تم التسعير',
      stage_negotiation:  'تفاوض',
      stage_won:          'تم الفوز',
      stage_lost:         'خسارة',
      src_walkin:         'زيارة شخصية',
      src_phone:          'هاتف',
      src_website:        'الموقع الإلكتروني',
      src_rep:            'مندوب مبيعات',
      lbl_follow_up:      'تاريخ المتابعة',
      lbl_priority:       'الأولوية',
      lbl_stage:          'المرحلة',
      lbl_product_type:   'نوع المنتج',
      lbl_source:         'مصدر العميل',
      lbl_rep:            'المندوب',
      status_booked:      'محجوز',
      status_paid:        'مدفوع',
      status_delayed:     'مؤجل',
      status_cancelled:   'ملغي',
      status_expired:     'منتهي الصلاحية',
      status_pending_conf:'بانتظار التأكيد',
      btn_add:            'إضافة',
      btn_save:           'حفظ',
      btn_cancel:         'إلغاء',
      btn_delete:         'حذف',
      btn_edit:           'تعديل',
      btn_close:          'إغلاق',
      // Leads page
      page_leads:         'إدارة العملاء المحتملين والفرص',
      btn_add_lead:       '← إضافة عميل محتمل',
      leads_all:          'الكل',
      lbl_name:           'الاسم',
      lbl_company:        'الشركة',
      lbl_notes:          'ملاحظات',
      th_waiting:         'مدة الانتظار',
      th_follow_up:       'المتابعة',
      th_product:         'المنتج',
      th_actions:         'إجراءات',
      leads_overdue_fu:   'متأخر',
      leads_dup_warn:     'تكرار محتمل — توجد سجلات مطابقة:',
      leads_none:         'لا يوجد عملاء محتملون بعد',
      leads_none_d:       'أضف أول عميل محتمل لبدء تتبع مسار المبيعات.',
      btn_convert:        'تحويل إلى عرض سعر',
      leads_converted:    'تم التحويل',
      modal_add_lead:     'إضافة عميل محتمل',
      modal_edit_lead:    'تعديل عميل محتمل',
      fu_required:        'يجب تحديد تاريخ المتابعة قبل الحفظ.',
      name_required:      'الاسم ورقم الهاتف مطلوبان.',
      toast_lead_saved:   'تم حفظ العميل المحتمل',
      toast_lead_deleted: 'تم حذف العميل المحتمل',
      toast_lead_converted:'تم تحويل العميل المحتمل إلى طلب عرض سعر',
      del_lead_t:         'حذف العميل المحتمل',
      del_lead_d:         'سيؤدي هذا إلى حذف العميل المحتمل نهائياً. لا يمكن التراجع عن هذا الإجراء.',
      ph_search_leads:    'البحث في العملاء المحتملين…',
      ph_rep_name:        'اسم المندوب…',
      ph_lead_notes:      'ملاحظات حول هذا العميل المحتمل…',
      // Sales Forms page
      page_sales_forms:   'نماذج المبيعات',
      sf_intro:           'أنشئ عرض سعر أو حجزاً نيابة عن العميل — للزيارات الشخصية أو الهاتف أو طلبات المندوبين.',
      sf_tab_concrete:    'حجز خرسانة',
      sf_tab_precast:     'عرض سعر مسبقة الصب',
      sf_tab_block:       'عرض سعر بلوك بناء',
      sf_client:          'اسم العميل',
      sf_location:        'موقع المشروع',
      sf_qty_m3:          'الكمية (م³)',
      sf_qty_units:       'الكمية (وحدة)',
      sf_qty_pcs:         'الكمية (قطعة)',
      sf_req_date:        'التاريخ المطلوب',
      sf_dispatch:        'الإطار الزمني للإرسال',
      sf_mix_grade:       'درجة الخلطة',
      sf_precast_product: 'منتج مسبق الصب',
      sf_block_product:   'منتج البلوك',
      sf_details:         'تفاصيل إضافية',
      sf_add_customer:    'إضافة هذا العميل إلى قاعدة بيانات العملاء',
      sf_existing_customer:'تمت مطابقة سجل عميل موجود — لن يتم إنشاء سجل مكرر.',
      sf_submit:          '← إنشاء وإرسال إلى سير العمل',
      sf_required_err:    'يرجى تعبئة جميع الحقول المطلوبة.',
      sf_success:         'تم الإنشاء بنجاح — الآن في عروض الأسعار وطلبات الحجز',
      sf_view_req:        '← عرض الطلبات',
      sf_approval_note:   'سيتطلب هذا الطلب موافقة:',
      apr_large_volume:   'حجز بكمية كبيرة',
      apr_high_discount:  'خصم أعلى من الحد المسموح',
      apr_same_day:       'إرسال عاجل في نفس اليوم',
      sf_dw_morning:      'صباحاً (06:00–10:00)',
      sf_dw_midday:       'منتصف اليوم (10:00–14:00)',
      sf_dw_afternoon:    'بعد الظهر (14:00–18:00)',
      sf_dw_evening:      'مساءً (18:00–22:00)',
      sf_dw_flexible:     'مرن',
      pc_hollow:          'بلاطات مجوفة',
      pc_wall:            'ألواح جدارية',
      pc_beam:            'كمرات وأعمدة',
      pc_stairs:          'سلالم',
      pc_boundary:        'أسوار حدودية',
      pc_custom:          'عنصر مخصص',
      bl_nh20:            'بلوك مفرغ عادي (20سم)',
      bl_ns20:            'بلوك مصمت عادي (20سم)',
      bl_ins20:           'بلوك معزول (20سم)',
      bl_ins30:           'بلوك معزول أزرق (30سم)',
      bl_wins30:          'بلوك معزول أبيض (30سم)',
      // Calendar page
      page_calendar:      'إدارة التقويم',
      cal_add_entry:      '← إضافة موعد',
      cal_export:         'تصدير',
      cal_export_day:     'اليوم (CSV)',
      cal_export_week:    'هذا الأسبوع (CSV)',
      cal_export_month:   'هذا الشهر (CSV)',
      cal_today:          'اليوم',
      cal_unassigned:     'قائمة غير المجدول',
      cal_unassigned_d:   'طلبات بدون تاريخ تسليم أو إطار زمني للإرسال.',
      cal_schedule:       'جدولة',
      cal_capacity:       'السعة اليومية',
      cal_conflict_window:'تعارض في الإطار الزمني للإرسال',
      cal_conflict_capacity:'تجاوز السعة اليومية',
      cal_tentative:      'مبدئي',
      cal_upcoming:       'القادم (خلال 3 أيام)',
      cal_none_upcoming:  'لا توجد مواعيد خلال الأيام الثلاثة القادمة.',
      cal_entry:          'موعد في التقويم',
      cal_day:            'اليوم',
      cal_qty:            'الكمية',
      cal_mark_tentative: 'حجز مبدئي (حجز مساحة قبل التأكيد)',
      cal_filter_region:  'تصفية حسب الموقع…',
      cal_filter_rep:     'تصفية حسب المندوب…',
      cal_empty_day:      'لا توجد مواعيد',
      toast_entry_saved:  'تم حفظ الموعد',
      toast_entry_deleted:'تم حذف الموعد',
      toast_rescheduled:  'تمت إعادة الجدولة',
      cal_linked_req:     'الطلب المرتبط',
      // Customer profile
      cust_profile:       'ملف العميل',
      cust_timeline:      'سجل النشاط',
      cust_key:           'عميل رئيسي',
      cust_mark_key:      'تحديد كعميل رئيسي (عميل متكرر مهم)',
      lbl_segment:        'الفئة',
      seg_none:           '— بدون —',
      seg_contractor:     'مقاول',
      seg_consultant:     'استشاري',
      seg_walkin:         'زيارة شخصية',
      seg_government:     'جهة حكومية',
      seg_retail:         'تجزئة',
      seg_developer:      'مطوّر عقاري',
      cust_stats:         'سجل المبيعات',
      cust_quotes_n:      'عروض الأسعار',
      cust_booked_n:      'محجوز / مدفوع',
      cust_volume_n:      'إجمالي الكمية',
      cust_no_timeline:   'لا يوجد نشاط مسجل بعد.',
      toast_cust_saved:   'تم حفظ العميل',
      flt_all_segments:   'كل الفئات',
      // Tasks page
      page_tasks:         'المهام والمتابعات',
      btn_add_task:       '← إضافة مهمة',
      task_all:           'الكل',
      task_open:          'مفتوحة',
      task_overdue:       'متأخرة',
      task_done:          'منجزة',
      task_title:         'المهمة',
      task_due:           'تاريخ الاستحقاق',
      task_assignee:      'مسندة إلى',
      task_link:          'السجل المرتبط',
      task_link_none:     '— غير مرتبطة —',
      task_link_request:  'عرض سعر / حجز',
      task_link_lead:     'عميل محتمل',
      task_link_customer: 'عميل',
      task_none:          'لا توجد مهام بعد',
      task_none_d:        'أنشئ مهام متابعة حتى لا يفوتك أي شيء.',
      task_mark_done:     'إنجاز',
      task_reopen:        'إعادة فتح',
      modal_add_task:     'إضافة مهمة',
      modal_edit_task:    'تعديل مهمة',
      task_title_req:     'عنوان المهمة وتاريخ الاستحقاق مطلوبان.',
      toast_task_saved:   'تم حفظ المهمة',
      toast_task_deleted: 'تم حذف المهمة',
      ph_task_title:      'مثال: الاتصال بالعميل بخصوص عرض C35…',
      ph_search_tasks:    'البحث في المهام…',
      // Sidebar
      nav_overview:       'نظرة عامة',
      nav_bookings:       'عروض الأسعار وطلبات الحجز',
      nav_inbox:          'صندوق الوارد',
      nav_profile:        'ملف تعريف الشركة',
      nav_upload_profile: 'رفع PDF',
      profile_no_upload:  'لم يتم رفع ملف بعد',
      profile_updated:    'تم تحديث ملف الشركة بنجاح!',
      nav_customers:      'قاعدة بيانات العملاء',
      nav_access:         'صلاحيات المستخدمين',
      nav_settings:       'الإعدادات',
      nav_role:           'مدير النظام',
      nav_back:           'العودة للموقع',
      nav_logout:         'تسجيل الخروج',
      // Overview
      page_overview:      'نظرة عامة على المبيعات',
      kpi_requests:       'إجمالي الطلبات',
      kpi_leads:          'عملاء جدد',
      kpi_volume:         'الحجم التقديري (م³)',
      kpi_quotes:         'عروض الأسعار النشطة',
      recent_title:       'طلبات عروض الأسعار الأخيرة',
      recent_view_all:    '← عرض الكل',
      th_client_name:     'اسم العميل',
      th_date:            'تاريخ التقديم',
      th_qty_m3:          'الكمية (م³)',
      th_status:          'الحالة',
      // Status badges
      status_pending_r:   'قيد المراجعة',
      status_pending:     'معلّق',
      status_quote_sent:  'تم إرسال العرض',
      status_approved:    'موافق عليه',
      status_contacted:   'تم التواصل',
      status_rejected:    'مرفوض',
      // Bookings
      page_bookings:      'عروض الأسعار وطلبات الحجز',
      btn_filter:         'تصفية',
      filter_by_status:   'تصفية حسب الحالة',
      filter_all:         'جميع الطلبات',
      filter_clear:       'مسح التصفية',
      label_quantity:     'الكمية',
      label_mix:          'نوع الخلطة',
      label_location:     'الموقع',
      label_client_msg:   'رسالة العميل',
      label_client:       'العميل',
      btn_gen_quote:      '← إنشاء عرض سعر',
      btn_upd_status:     'تحديث الحالة',
      // Quote modal
      modal_gen_quote:    'إنشاء عرض سعر',
      modal_client:       'العميل',
      modal_qty:          'الكمية',
      modal_mix:          'نوع الخلطة',
      modal_price:        'السعر لكل م³ (ر.س)',
      modal_total:        'الإجمالي (ر.س)',
      modal_delivery:     'تاريخ التسليم',
      modal_notes:        'ملاحظات للعميل',
      modal_cancel:       'إلغاء',
      modal_send_quote:   'إرسال العرض',
      toast_quote_sent:   'تم إرسال عرض السعر بنجاح!',
      modal_discount:     'الخصم (٪)',
      modal_expiry:       'انتهاء صلاحية العرض',
      modal_reason:       'سبب التعديل',
      ph_reason:          'ما سبب تعديل عرض السعر؟',
      apr_submitted:      'تم حفظ العرض وإرساله للموافقة. سيُرسل البريد الإلكتروني للعميل بعد الموافقة.',
      apr_pending_banner: 'بانتظار الموافقة — تم تعليق إرسال البريد للعميل.',
      apr_rejected_banner:'تم رفض الموافقة.',
      exp_expires:        'ينتهي في',
      flt_all_products:   'كل المنتجات',
      // Status modal
      modal_upd_status:   'تحديث الحالة',
      modal_new_status:   'الحالة الجديدة',
      modal_int_note:     'ملاحظة داخلية (اختياري)',
      modal_save_status:  'حفظ الحالة',
      toast_status_saved: 'تم تحديث الحالة بنجاح!',
      // Inbox
      page_inbox:         'صندوق الوارد',
      tab_all:            'الكل',
      tab_unread:         'غير مقروء',
      tab_flagged:        'مميّز',
      btn_send_reply:     'إرسال الرد',
      // Customers
      page_customers:     'قاعدة بيانات العملاء',
      btn_export:         'تصدير CSV',
      btn_add_record:     '← إضافة سجل',
      btn_sort:           'ترتيب',
      th_cust_name:       'اسم العميل',
      th_email:           'البريد الإلكتروني',
      th_phone:           'الهاتف',
      th_last_activity:   'آخر نشاط',
      th_location_c:      'الموقع',
      action_view:        '← عرض التفاصيل',
      pagination_cust:    'عرض 1 إلى 4 من أصل 97 نتيجة',
      // Access
      page_access:        'إدارة الصلاحيات',
      btn_add_user:       '← إضافة مستخدم',
      active_personnel:   'الموظفون النشطون',
      th_name:            'الاسم',
      th_role_a:          'الدور',
      th_status_a:        'الحالة',
      status_active:      'نشط',
      status_inactive:    'غير نشط',
      action_manage:      'إدارة',
      pagination_access:  'عرض 1 إلى 3 من أصل 12 موظفاً',
      module_access:      'التحكم في صلاحيات الوحدات',
      access_bookings:    'طلبات عروض الأسعار',
      access_bookings_d:  'عرض وإدارة الحجوزات',
      access_financials:  'الشؤون المالية',
      access_fin_d:       'الوصول إلى التقارير المالية',
      access_customers:   'بيانات العملاء',
      access_cust_d:      'عرض قاعدة بيانات العملاء',
      access_settings:    'إعدادات النظام',
      access_sett_d:      'تعديل إعدادات النظام',
      btn_save_config:    'حفظ الإعدادات',
      btn_revoke:         'إلغاء جميع الصلاحيات',
      // Settings
      page_settings:      'الإعدادات',
      btn_save_changes:   'حفظ التغييرات',
      toast_saved:        'تم حفظ الإعدادات بنجاح',
      sect_company:       'معلومات الشركة',
      lbl_co_name:        'اسم الشركة',
      lbl_website:        'رابط الموقع',
      lbl_co_email:       'البريد الإلكتروني',
      lbl_co_phone:       'رقم الهاتف',
      lbl_address:        'عنوان المقر الرئيسي',
      sect_account:       'الحساب وكلمة المرور',
      lbl_username:       'اسم المستخدم',
      lbl_cur_pass:       'كلمة المرور الحالية',
      lbl_new_pass:       'كلمة المرور الجديدة',
      lbl_confirm_pass:   'تأكيد كلمة المرور الجديدة',
      sect_notif:         'تفضيلات الإشعارات',
      notif1_t:           'طلب حجز جديد',
      notif1_d:           'تلقّي إشعار عند تقديم طلب حجز خرسانة جديد',
      notif2_t:           'رسالة واردة جديدة',
      notif2_d:           'تلقّي إشعار عند إرسال العميل نموذج تواصل',
      notif3_t:           'سجل عميل جديد',
      notif3_d:           'تنبيه عند إضافة عميل جديد إلى قاعدة البيانات',
      notif4_t:           'تقرير ملخص أسبوعي',
      notif4_d:           'استلام ملخص أسبوعي للطلبات والعملاء والكميات',
      sect_system:        'تفضيلات النظام',
      lbl_lang:           'اللغة الافتراضية',
      lbl_tz:             'المنطقة الزمنية',
      lbl_date_fmt:       'تنسيق التاريخ',
      lbl_vol_unit:       'وحدة الحجم',
      sect_danger:        'منطقة الخطر',
      danger_t:           'مسح جميع سجلات الحجز',
      danger_d:           'حذف جميع طلبات الحجز نهائياً من النظام. لا يمكن التراجع عن هذا الإجراء.',
      btn_clear:          'مسح السجلات',
      // Login
      login_heading:      'دخول',
      login_sub:          'للموظفين المصرح لهم فقط',
      lbl_username_l:     'اسم المستخدم / البريد الإلكتروني',
      lbl_password:       'كلمة المرور',
      forgot_pw:          'نسيت كلمة المرور؟',
      btn_login:          '← تسجيل الدخول',
      login_footer:       'بيئة نظام آمنة',
      // Placeholders
      ph_search:          'بحث…',
      ph_search_req:      'البحث في الطلبات…',
      ph_search_cust:     'البحث في العملاء…',
      ph_search_pers:     'البحث في الموظفين…',
      ph_username:        'أدخل اسم المستخدم أو البريد الإلكتروني',
      ph_password:        'أدخل كلمة المرور',
      ph_reply:           'اكتب ردك…',
      ph_int_note:        'أضف ملاحظة داخلية حول تغيير الحالة…',
      ph_notes:           'أضف ملاحظات التسليم أو الشروط أو التعليمات…',
    }
  };

  // RTL CSS injected when Arabic is active
  var RTL_CSS = [
    'html[dir=rtl] body, html[dir=rtl] p, html[dir=rtl] span:not(.material-symbols-outlined),',
    'html[dir=rtl] a, html[dir=rtl] button, html[dir=rtl] label,',
    'html[dir=rtl] input, html[dir=rtl] textarea, html[dir=rtl] select,',
    'html[dir=rtl] td, html[dir=rtl] th { font-family: "Tajawal", Arial, sans-serif !important; }',
    'html[dir=rtl] h1, html[dir=rtl] h2, html[dir=rtl] h3,',
    'html[dir=rtl] h4, html[dir=rtl] h5 {',
    '  font-family: "Tajawal", Arial, sans-serif !important;',
    '  letter-spacing: 0 !important; }',
    'html[dir=rtl] .tracking-wide,',
    'html[dir=rtl] .tracking-widest { letter-spacing: 0 !important; }',
    /* Sidebar border — sidebar moves to the right in RTL, so the inner border flips */
    'html[dir=rtl] aside { border-right: 0 !important; border-left: 1px solid #DCDBD7 !important; }',
    /* Inbox message list pane */
    'html[dir=rtl] .rtl-border-flip { border-right: 0 !important; border-left: 1px solid #DCDBD7 !important; }',
    /* Booking card detail pane (border-l) */
    'html[dir=rtl] .rtl-border-iflip { border-left: 0 !important; border-right: 1px solid #DCDBD7 !important; }',
    /* Table text */
    'html[dir=rtl] th.text-left, html[dir=rtl] td.text-left { text-align: right; }',
    'html[dir=rtl] .text-right { text-align: left; }',
    /* Icon search field — mirror padding */
    'html[dir=rtl] .rtl-search { padding-left: 1rem !important; padding-right: 2.5rem !important; }',
    'html[dir=rtl] .rtl-icon-r { left: auto !important; right: 0.75rem !important; }',
  ].join('\n');

  var currentLang = localStorage.getItem('dashLang') || 'en';

  function applyDashLang(lang) {
    currentLang = lang;
    localStorage.setItem('dashLang', lang);
    var t = T[lang];
    var isAr = lang === 'ar';

    // Set html attributes
    document.documentElement.lang = lang;
    document.documentElement.dir = isAr ? 'rtl' : 'ltr';

    // Inject / clear RTL stylesheet
    var styleEl = document.getElementById('dash-rtl-css');
    if (isAr) {
      if (!styleEl) {
        styleEl = document.createElement('style');
        styleEl.id = 'dash-rtl-css';
        document.head.appendChild(styleEl);
      }
      styleEl.textContent = RTL_CSS;
    } else {
      if (styleEl) styleEl.textContent = '';
    }

    // Translate text content
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (t[key] !== undefined) el.textContent = t[key];
    });

    // Translate placeholders
    document.querySelectorAll('[data-i18n-ph]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-ph');
      if (t[key] !== undefined) el.placeholder = t[key];
    });

    // Update toggle button label
    var btn = document.getElementById('dash-lang-btn');
    if (btn) btn.textContent = isAr ? 'English' : 'عربي';
  }

  window.toggleDashLang = function () {
    applyDashLang(currentLang === 'en' ? 'ar' : 'en');
  };

  // Dictionary lookup for JS-composed strings (toasts, dynamic labels).
  window.dashT = function (key, fallback) {
    var t = T[currentLang] || {};
    return t[key] !== undefined ? t[key] : (fallback !== undefined ? fallback : key);
  };

  // Re-apply the CURRENT language to the whole document. Call this
  // after dynamically injecting new [data-i18n] nodes so they translate.
  window.reapplyDashLang = function () { applyDashLang(currentLang); };

  // Auto-apply on page load
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { applyDashLang(currentLang); });
  } else {
    applyDashLang(currentLang);
  }

}());
