// Dashboard bilingual support — English / Arabic
(function () {

  var T = {
    en: {
      // Sidebar — Sales System
      nav_sales_system:   'Sales System',
      nav_sales_overview: 'Sales Overview',
      nav_leads:          'Leads & Opportunities',
      nav_quotes_bookings:'Quotes & Booking Requests',
      nav_sales_forms:    'Sales Forms',
      nav_calendar:       'Calendar Management',
      nav_tasks:          'Tasks & Follow-Ups',
      nav_reports:        'Reports & Analytics',
      nav_approvals:      'Approvals & Audit',
      // Shared sales vocabulary
      product_concrete:   'Concrete',
      product_precast:    'Precast',
      product_block:      'Construction Block',
      priority_high:      'High',
      priority_medium:    'Medium',
      priority_low:       'Low',
      stage_new:          'New',
      stage_contacted:    'Contacted',
      stage_qualified:    'Qualified',
      stage_quoted:       'Quoted',
      stage_negotiation:  'Negotiation',
      stage_won:          'Won',
      stage_lost:         'Lost',
      src_walkin:         'Walk-in',
      src_phone:          'Phone',
      src_website:        'Website',
      src_rep:            'Representative',
      lbl_follow_up:      'Follow-up Date',
      lbl_priority:       'Priority',
      lbl_stage:          'Stage',
      lbl_product_type:   'Product Type',
      lbl_source:         'Lead Source',
      lbl_rep:            'Representative',
      status_booked:      'Booked',
      status_paid:        'Paid',
      status_delayed:     'Delayed',
      status_cancelled:   'Cancelled',
      status_expired:     'Expired',
      status_pending_conf:'Pending Confirmation',
      btn_add:            'Add',
      btn_save:           'Save',
      btn_cancel:         'Cancel',
      btn_delete:         'Delete',
      btn_edit:           'Edit',
      btn_close:          'Close',
      // Leads page
      page_leads:         'Lead & Opportunity Management',
      btn_add_lead:       'Add Lead →',
      leads_all:          'All',
      lbl_name:           'Name',
      lbl_company:        'Company',
      lbl_notes:          'Notes',
      th_waiting:         'Waiting',
      th_follow_up:       'Follow-up',
      th_product:         'Product',
      th_actions:         'Actions',
      leads_overdue_fu:   'Overdue',
      leads_dup_warn:     'Possible duplicate — matching records found:',
      leads_none:         'No leads yet',
      leads_none_d:       'Add your first lead to start tracking the sales pipeline.',
      btn_convert:        'Convert to Quote',
      leads_converted:    'Converted',
      modal_add_lead:     'Add Lead',
      modal_edit_lead:    'Edit Lead',
      fu_required:        'A follow-up date is required before saving.',
      name_required:      'Name and phone are required.',
      toast_lead_saved:   'Lead saved',
      toast_lead_deleted: 'Lead deleted',
      toast_lead_converted:'Lead converted to a quote request',
      del_lead_t:         'Delete Lead',
      del_lead_d:         'This permanently removes the lead. This cannot be undone.',
      ph_search_leads:    'Search leads…',
      ph_rep_name:        'Representative name…',
      ph_lead_notes:      'Notes about this lead…',
      // Sales Forms page
      page_sales_forms:   'Sales Forms',
      sf_intro:           'Create a quote or booking on behalf of a client — walk-in, phone, or representative requests.',
      sf_tab_concrete:    'Concrete Booking',
      sf_tab_precast:     'Precast Quote',
      sf_tab_block:       'Construction Block Quote',
      sf_client:          'Client Name',
      sf_location:        'Project Location',
      sf_qty_m3:          'Quantity (m³)',
      sf_qty_units:       'Quantity (units)',
      sf_qty_pcs:         'Quantity (pieces)',
      sf_req_date:        'Required Date',
      sf_dispatch:        'Dispatch Time Frame',
      sf_mix_grade:       'Mix Grade',
      sf_precast_product: 'Precast Product',
      sf_block_product:   'Block Product',
      sf_details:         'Additional Details',
      sf_add_customer:    'Add this client to the Customer Database',
      sf_existing_customer:'Matched an existing customer record — no duplicate will be created.',
      sf_submit:          'Create & Send to Workflow →',
      sf_required_err:    'Please fill all required fields.',
      sf_success:         'Created successfully — now in Quotes & Booking Requests',
      sf_view_req:        'View Requests →',
      sf_approval_note:   'This request will require approval:',
      apr_large_volume:   'Large volume booking',
      apr_high_discount:  'Discount above threshold',
      apr_same_day:       'Urgent same-day dispatch',
      sf_dw_morning:      'Morning (06:00–10:00)',
      sf_dw_midday:       'Midday (10:00–14:00)',
      sf_dw_afternoon:    'Afternoon (14:00–18:00)',
      sf_dw_evening:      'Evening (18:00–22:00)',
      sf_dw_flexible:     'Flexible',
      pc_hollow:          'Hollow-core Slabs',
      pc_wall:            'Wall Panels',
      pc_beam:            'Beams & Columns',
      pc_stairs:          'Stairs',
      pc_boundary:        'Boundary Walls',
      pc_custom:          'Custom Element',
      bl_nh20:            'Normal Hollow Block (20cm)',
      bl_ns20:            'Normal Solid Block (20cm)',
      bl_ins20:           'Insulated Block (20cm)',
      bl_ins30:           'Blue Insulated Block (30cm)',
      bl_wins30:          'White Insulated Block (30cm)',
      // Calendar page
      page_calendar:      'Calendar Management',
      cal_add_entry:      'Add Entry →',
      cal_export:         'Export',
      cal_export_day:     'Today (CSV)',
      cal_export_week:    'This Week (CSV)',
      cal_export_month:   'This Month (CSV)',
      cal_today:          'Today',
      cal_unassigned:     'Unassigned Queue',
      cal_unassigned_d:   'Requests without a delivery date or dispatch window.',
      cal_schedule:       'Schedule',
      cal_capacity:       'Daily capacity',
      cal_conflict_window:'Dispatch window overlap',
      cal_conflict_capacity:'Daily capacity exceeded',
      cal_tentative:      'Tentative',
      cal_upcoming:       'Upcoming (next 3 days)',
      cal_none_upcoming:  'Nothing scheduled in the next 3 days.',
      cal_entry:          'Calendar Entry',
      cal_day:            'Day',
      cal_qty:            'Quantity',
      cal_mark_tentative: 'Tentative booking (reserve space before confirmation)',
      cal_filter_region:  'Filter by location…',
      cal_filter_rep:     'Filter by representative…',
      cal_empty_day:      'No entries',
      toast_entry_saved:  'Calendar entry saved',
      toast_entry_deleted:'Calendar entry deleted',
      toast_rescheduled:  'Rescheduled',
      cal_linked_req:     'Linked request',
      // Customer profile
      cust_profile:       'Customer Profile',
      cust_timeline:      'Activity Timeline',
      cust_key:           'Key Account',
      cust_mark_key:      'Mark as key account (important repeat customer)',
      lbl_segment:        'Segment',
      seg_none:           '— None —',
      seg_contractor:     'Contractor',
      seg_consultant:     'Consultant',
      seg_walkin:         'Walk-in',
      seg_government:     'Government',
      seg_retail:         'Retail',
      seg_developer:      'Developer',
      cust_stats:         'Sales History',
      cust_quotes_n:      'Quotes',
      cust_booked_n:      'Booked / Paid',
      cust_volume_n:      'Total Volume',
      cust_no_timeline:   'No activity recorded yet.',
      toast_cust_saved:   'Customer saved',
      flt_all_segments:   'All Segments',
      // Tasks page
      page_tasks:         'Tasks & Follow-Ups',
      btn_add_task:       'Add Task →',
      task_all:           'All',
      task_open:          'Open',
      task_overdue:       'Overdue',
      task_done:          'Done',
      task_title:         'Task',
      task_due:           'Due Date',
      task_assignee:      'Assigned To',
      task_link:          'Related Record',
      task_link_none:     '— Not linked —',
      task_link_request:  'Quote / Booking',
      task_link_lead:     'Lead',
      task_link_customer: 'Customer',
      task_none:          'No tasks yet',
      task_none_d:        'Create follow-up tasks so nothing slips through the cracks.',
      task_mark_done:     'Mark done',
      task_reopen:        'Reopen',
      modal_add_task:     'Add Task',
      modal_edit_task:    'Edit Task',
      task_title_req:     'A task title and due date are required.',
      toast_task_saved:   'Task saved',
      toast_task_deleted: 'Task deleted',
      ph_task_title:      'e.g. Call client about the C35 quote…',
      ph_search_tasks:    'Search tasks…',
      // Sales Overview additions
      ov_pipeline:        'Lead Pipeline',
      ov_followups:       'Overdue Follow-Ups',
      ov_upcoming:        'Upcoming Deliveries (7 days)',
      ov_open_leads:      'Open Leads',
      ov_pending_q:       'Pending Quotes',
      ov_upcoming_b:      'Upcoming Bookings',
      ov_overdue_f:       'Overdue Follow-Ups',
      ov_pending_apr:     'Pending Approvals',
      kpi_hint_pending:   'Pending requests',
      kpi_hint_awaiting:  'Awaiting client',
      ov_no_leads:        'No leads in the pipeline yet — add one in Leads & Opportunities.',
      ov_no_overdue:      'Nothing overdue — great job staying on top of follow-ups!',
      ov_no_upcoming:     'No deliveries scheduled in the next 7 days.',
      // Reports page
      page_reports:       'Sales Reports & Analytics',
      rpt_category:       'Category Performance',
      rpt_requests:       'Requests',
      rpt_quoted_value:   'Quoted Value (SAR)',
      rpt_booked:         'Booked / Paid',
      rpt_volume:         'Volume',
      rpt_funnel:         'Pipeline Conversion',
      rpt_f_inquiries:    'Inquiries',
      rpt_f_quoted:       'Quoted',
      rpt_f_confirmed:    'Confirmed (Booked / Paid)',
      rpt_f_closed:       'Closed / Delivered',
      rpt_conv_rate:      'Quote Conversion Rate',
      rpt_conv_d:         'Quotes that became confirmed business',
      rpt_reps:           'Representative Performance',
      rpt_rep_leads:      'Leads',
      rpt_rep_requests:   'Requests',
      rpt_rep_won:        'Won / Booked',
      rpt_rep_conv:       'Conversion',
      rpt_no_reps:        'No representative-sourced records yet.',
      rpt_customers:      'Customer Insights',
      rpt_top_customers:  'Top Customers',
      rpt_repeat:         'Repeat Clients',
      rpt_keys:           'Key Accounts',
      rpt_no_cust:        'No customer activity yet.',
      rpt_ops:            'Operational Trends',
      rpt_delayed:        'Delayed Jobs',
      rpt_expired:        'Expired Quotes',
      rpt_load7:          '7-Day Booking Load (m³)',
      rpt_fu_compliance:  'Follow-Up Compliance',
      rpt_total:          'Total',
      rpt_export_csv:     'Export CSV',
      rpt_print:          'Print / PDF',
      // ── Plant Operations ──
      nav_ops_system:     'Plant Operations',
      nav_ops_board:      'Operations Board',
      nav_ops_orders:     'Orders from Sales',
      nav_ops_fleet:      'Fleet & Master Data',
      nav_ops_reports:    'Ops Reports',
      access_operations:  'Plant Operations',
      access_operations_d:'Dispatch board, orders intake, fleet and ops reports',
      // ops statuses
      ops_booked:         'Booked',
      ops_authorized:     'Authorized',
      ops_on_hold:        'On Hold',
      ops_scheduled:      'Scheduled',
      ops_batching:       'Batching',
      ops_loading:        'Loading',
      ops_en_route:       'En Route',
      ops_on_site:        'On Site',
      ops_discharging:    'Discharging',
      ops_washout:        'Washout',
      ops_returned:       'Returned',
      ops_completed:      'Completed',
      ops_delayed:        'Delayed',
      ops_pending_review: 'Pending Review',
      // delay reasons
      dly_traffic:        'Traffic',
      dly_plant:          'Plant Breakdown',
      dly_pump:           'Pump Breakdown',
      dly_truck:          'Truck Breakdown',
      dly_site:           'Site Not Ready',
      dly_weather:        'Weather',
      dly_quality:        'Quality Issue',
      dly_customer:       'Customer Delay',
      dly_other:          'Other',
      // reject reasons
      rej_slump:          'Slump Out of Spec',
      rej_wait:           'Excess Wait Time',
      rej_mix:            'Wrong Mix',
      rej_site:           'Site Rejection',
      rej_other:          'Other',
      // shifts
      shift_morning:      'Morning',
      shift_evening:      'Evening',
      shift_night:        'Night',
      // orders page
      page_ops_orders:    'Orders from Sales',
      oo_intro:           'Concrete bookings synced from the Sales System. Sales owns the commercial data — operations adds execution details only.',
      oo_sync:            'Sync from Sales',
      oo_synced_n:        'new order(s) synced',
      oo_none:            'No operational orders yet',
      oo_none_d:          'Confirmed concrete bookings from the Sales System will appear here automatically.',
      oo_commercial:      'Commercial (from Sales — read only)',
      oo_execution:       'Execution (operations)',
      oo_auth_status:     'Authorization',
      oo_site_ready:      'Site readiness confirmed (required before dispatch)',
      oo_plant:           'Plant',
      oo_no_plant:        '— No plant assigned —',
      oo_priority:        'Job Priority',
      pri_urgent:         'Urgent',
      pri_high:           'High',
      pri_normal:         'Normal',
      pri_low:            'Low',
      oo_notes:           'Operational Notes',
      oo_mark_complete:   'Mark Job Completed',
      oo_completed_note:  'Completion is shared back to the Sales System (stage: Delivered).',
      oo_trips:           'trips',
      oo_view_board:      'Open on Board →',
      toast_oo_saved:     'Order updated',
      toast_oo_completed: 'Job completed — Sales updated to Delivered',
      // board page
      page_ops_board:     'Operations Board',
      ob_today:           'Today',
      ob_capacity:        'Daily Capacity',
      ob_alerts:          'Exception Alerts',
      ob_no_alerts:       'No exceptions — operations running clean.',
      ob_unscheduled:     'Authorized — awaiting trips',
      ob_no_orders:       'Nothing scheduled for this day.',
      ob_add_trip:        'Add Trip',
      ob_trip:            'Trip',
      ob_truck:           'Mixer Truck',
      ob_pump:            'Pump',
      ob_no_pump:         '— No pump —',
      ob_driver:          'Driver',
      ob_load_time:       'Load Time',
      ob_qty:             'Load (m³)',
      ob_advance:         'Next milestone',
      ob_mark_delay:      'Flag Delay',
      ob_delay_reason:    'Delay Reason',
      ob_reject_load:     'Reject Load',
      ob_reject_reason:   'Rejection Reason',
      ob_busy_warn:       'This asset is already assigned to another active trip on this day.',
      ob_trip_done:       'Trip completed',
      ob_alert_delay:     'delayed',
      ob_alert_overcap:   'Capacity exceeded',
      ob_alert_conflict:  'Asset conflict',
      ob_alert_pending:   'awaiting authorization with delivery today',
      toast_trip_saved:   'Trip saved',
      toast_trip_deleted: 'Trip removed',
      // fleet page
      page_ops_fleet:     'Fleet & Master Data',
      fl_plants:          'Plants',
      fl_mixers:          'Mixer Trucks',
      fl_pumps:           'Pump Trucks',
      fl_staff:           'Plant Staff',
      fl_add:             'Add →',
      fl_name:            'Name / ID',
      fl_capacity:        'Capacity',
      fl_boom:            'Boom (m)',
      fl_operator:        'Operator / Driver',
      fl_role:            'Role',
      fl_shift:           'Shift',
      fl_status:          'Status',
      ast_available:      'Available',
      ast_on_trip:        'On Trip',
      ast_maintenance:    'Maintenance',
      fl_trips_today:     'Trips today',
      fl_none:            'Nothing here yet — add your first record.',
      fl_del_t:           'Delete record',
      fl_del_d:           'This permanently removes the record. This cannot be undone.',
      toast_ast_saved:    'Record saved',
      toast_ast_deleted:  'Record deleted',
      role_dispatcher:    'Dispatcher',
      role_supervisor:    'Plant Supervisor',
      role_operator:      'Plant Operator',
      role_driver:        'Driver',
      role_pump_op:       'Pump Operator',
      role_fleet:         'Fleet Coordinator',
      // ops reports
      page_ops_reports:   'Operations Reports & Analytics',
      or_production:      'Production — Planned vs Actual (7 days)',
      or_planned:         'Planned',
      or_actual:          'Delivered',
      or_ontime:          'On-Time Dispatch',
      or_ontime_d:        'Trips loaded within their planned window',
      or_turnaround:      'Avg Truck Turnaround',
      or_mins:            'min',
      or_truck_util:      'Mixer Utilization',
      or_pump_util:       'Pump Utilization',
      or_delays:          'Delays by Reason',
      or_no_delays:       'No delays recorded.',
      or_rejected:        'Rejected Loads',
      or_clients:         'Client Service Performance',
      or_client:          'Client',
      or_jobs:            'Jobs',
      or_volume:          'Delivered (m³)',
      or_trips:           'Trips',
      or_delays_n:        'Delays',
      or_no_data:         'No operational data yet.',
      // ── Precast Operations ──
      nav_pc_system:      'Precast Operations',
      nav_pc_orders:      'Precast Orders',
      nav_pc_production:  'Production Queue',
      nav_pc_delivery:    'Delivery Planning',
      nav_pc_reports:     'Precast Reports',
      access_precast:     'Precast Operations',
      access_precast_d:   'Precast orders, production queue, delivery planning and reports',
      fl_molds:           'Molds & Lines',
      fl_trailers:        'Trailers',
      // precast statuses
      pc_design_review:   'Design Review',
      pc_queued:          'Queued',
      pc_mold_prep:       'Mold Prep',
      pc_casting:         'Casting',
      pc_curing:          'Curing',
      pc_demolding:       'Demolding',
      pc_qc:              'QC',
      pc_in_yard:         'In Yard',
      pc_in_production:   'In Production',
      pc_ready_yard:      'Ready in Yard',
      pc_delivering:      'Delivering',
      pc_planned:         'Planned',
      pc_delivered:       'Delivered',
      // QC reasons
      qc_surface:         'Surface Defect',
      qc_dimension:       'Dimensional Error',
      qc_crack:           'Cracking',
      qc_rebar:           'Reinforcement Issue',
      qc_curing:          'Curing Problem',
      qc_other:           'Other',
      // design
      ds_awaiting:        'Awaiting Drawings',
      ds_approved:        'Design Approved',
      po_design:          'Design Status',
      // orders page
      page_pc_orders:     'Precast Orders',
      po_intro:           'Precast orders synced from the Sales System. Sales owns the commercial data — precast operations adds design, production and delivery execution.',
      po_none:            'No precast orders yet',
      po_none_d:          'Confirmed precast quotes from the Sales System will appear here automatically.',
      po_units:           'units',
      po_castings:        'castings',
      po_deliveries:      'deliveries',
      po_open_production: 'Open Production →',
      po_open_delivery:   'Open Delivery →',
      po_yard:            'In yard',
      po_delivered_n:     'Delivered',
      toast_po_saved:     'Order updated',
      toast_po_completed: 'Job completed — Sales updated to Delivered',
      // production page
      page_pc_production: 'Production Queue',
      pp_line_capacity:   'Line Capacity',
      pp_no_lines:        'No production lines yet — add Molds & Lines in Fleet & Master Data.',
      pp_add_casting:     'Add Casting',
      pp_line:            'Line / Mold',
      pp_element:         'Element',
      pp_units:           'Units',
      pp_cast_day:        'Casting Day',
      pp_qc_pass:         'QC Pass',
      pp_qc_fail:         'QC Fail',
      pp_qc_reason:       'QC Failure Reason',
      pp_no_orders:       'No authorized precast orders in production.',
      pp_awaiting_design: 'Awaiting design approval',
      pp_over_line:       'Line capacity exceeded',
      pp_alert_qc:        'QC failure',
      toast_cast_saved:   'Casting saved',
      toast_cast_deleted: 'Casting removed',
      // delivery page
      page_pc_delivery:   'Delivery Planning',
      pd_add:             'Add Delivery',
      pd_trailer:         'Trailer',
      pd_no_trailer:      '— No trailer —',
      pd_items:           'Load List',
      pd_day:             'Delivery Day',
      pd_none:            'No deliveries planned.',
      pd_yard_ready:      'Ready in yard',
      pd_yard_short:      'Units in yard are less than this load',
      pd_alert_delay:     'Delivery delayed',
      toast_del_saved:    'Delivery saved',
      toast_del_deleted:  'Delivery removed',
      // reports page
      page_pc_reports:    'Precast Reports & Analytics',
      pr_output:          'Production Output — Cast vs Delivered (7 days)',
      pr_cast:            'Cast',
      pr_delivered:       'Delivered',
      pr_qc_rate:         'QC Pass Rate',
      pr_qc_d:            'Castings that passed quality control',
      pr_ontime:          'On-Time Delivery',
      pr_line_util:       'Line Utilization',
      pr_trailer_util:    'Trailer Utilization',
      pr_qc_fails:        'QC Failures by Reason',
      pr_no_qc:           'No QC failures recorded.',
      pr_elements:        'Output by Element',
      pr_element:         'Element',
      pr_orders_n:        'Orders',
      // Approvals & Audit page
      page_approvals:     'Approval & Audit System',
      apr_queue:          'Pending Approvals',
      apr_queue_d:        'Quotes and bookings waiting for an administrator decision.',
      apr_none:           'Nothing waiting for approval.',
      apr_approve:        'Approve',
      apr_reject:         'Reject',
      apr_note_ph:        'Optional note for this decision…',
      apr_approved_toast: 'Approved — the quote email was released to the client.',
      apr_approved_noemail:'Approved. No client email on file, so nothing was sent.',
      apr_rejected_toast: 'Rejected — the request was returned to Pending.',
      apr_capacity:       'Concrete Capacity — Next 7 Days',
      apr_capacity_d:     'Daily booked volume vs the 600 m³ capacity. Overbooked days stay allowed but are flagged for manual override.',
      apr_audit:          'Audit Log',
      apr_audit_d:        'Quote revisions, status changes, approvals, and other important actions.',
      apr_no_audit:       'No audit entries yet.',
      th_action:          'Action',
      th_detail:          'Detail',
      th_by:              'By',
      ph_search_audit:    'Search audit log…',
      apr_reasons:        'Reasons',
      // Sidebar
      nav_overview:       'Overview',
      nav_bookings:       'Quotes & Booking Requests',
      nav_inbox:          'Inbox',
      nav_profile:        'Company Profile',
      nav_upload_profile: 'Upload PDF',
      profile_no_upload:  'No profile uploaded yet',
      profile_updated:    'Company profile updated successfully!',
      nav_customers:      'Customer Database',
      nav_access:         'User Access',
      nav_settings:       'Settings',
      nav_role:           'System Manager',
      nav_back:           'Back to Website',
      nav_logout:         'Logout',
      // Overview
      page_overview:      'Sales Overview',
      kpi_requests:       'Total Requests',
      kpi_leads:          'New Leads',
      kpi_volume:         'Est. Volume (m³)',
      kpi_quotes:         'Active Quotes',
      recent_title:       'Recent Quote Requests',
      recent_view_all:    'View All →',
      th_client_name:     'Client Name',
      th_date:            'Date Submitted',
      th_qty_m3:          'Quantity (m³)',
      th_status:          'Status',
      // Status badges
      status_pending_r:   'Pending Review',
      status_pending:     'Pending',
      status_quote_sent:  'Quote Sent',
      status_approved:    'Approved',
      status_contacted:   'Contacted',
      status_rejected:    'Rejected',
      // Bookings
      page_bookings:      'Quotes & Booking Requests',
      btn_filter:         'Filter',
      filter_by_status:   'Filter by Status',
      filter_all:         'All Requests',
      filter_clear:       'Clear filters',
      label_quantity:     'Quantity',
      label_mix:          'Mix Type',
      label_location:     'Location',
      label_client_msg:   'Client Message',
      label_client:       'Client',
      btn_gen_quote:      'Generate Quote →',
      btn_upd_status:     'Update Status',
      // Quote modal
      modal_gen_quote:    'Generate Quote',
      modal_client:       'Client',
      modal_qty:          'Quantity',
      modal_mix:          'Mix Type',
      modal_price:        'Price per m³ (SAR)',
      modal_total:        'Total (SAR)',
      modal_delivery:     'Delivery Date',
      modal_notes:        'Notes to Client',
      modal_cancel:       'Cancel',
      modal_send_quote:   'Send Quote',
      toast_quote_sent:   'Quote sent successfully!',
      modal_discount:     'Discount (%)',
      modal_expiry:       'Quote Expiry',
      modal_reason:       'Reason for Change',
      ph_reason:          'Why is this quote being revised?',
      apr_submitted:      'Quote saved and submitted for approval. The client email will be sent after approval.',
      err_past_date:      'The date cannot be in the past — concrete cannot be booked for a day that has already gone.',
      apr_pending_banner: 'Awaiting approval — client email is on hold.',
      apr_rejected_banner:'Approval rejected.',
      exp_expires:        'Expires',
      flt_all_products:   'All Products',
      // Status modal
      modal_upd_status:   'Update Status',
      modal_new_status:   'New Status',
      modal_int_note:     'Internal Note (optional)',
      modal_save_status:  'Save Status',
      toast_status_saved: 'Status updated successfully!',
      // Inbox
      page_inbox:         'Inbox',
      tab_all:            'All',
      tab_unread:         'Unread',
      tab_flagged:        'Flagged',
      btn_send_reply:     'Send Reply',
      // Customers
      page_customers:     'Customer Database',
      btn_export:         'Export CSV',
      btn_add_record:     'Add Record →',
      btn_sort:           'Sort',
      th_cust_name:       'Customer Name',
      th_email:           'Email',
      th_phone:           'Phone',
      th_last_activity:   'Last Activity',
      th_location_c:      'Location',
      action_view:        'View Details →',
      pagination_cust:    'Showing 1 to 4 of 97 results',
      // Access
      page_access:        'Access Management',
      btn_add_user:       'Add User →',
      active_personnel:   'Active Personnel',
      th_name:            'Name',
      th_role_a:          'Role',
      th_status_a:        'Status',
      status_active:      'Active',
      status_inactive:    'Inactive',
      action_manage:      'Manage',
      pagination_access:  'Showing 1 to 3 of 12 personnel',
      module_access:      'Module Access Control',
      access_bookings:    'Quote Requests',
      access_bookings_d:  'View and manage bookings',
      access_financials:  'Financials',
      access_fin_d:       'Access financial reports',
      access_customers:   'Customer Data',
      access_cust_d:      'View customer database',
      access_settings:    'System Settings',
      access_sett_d:      'Modify system configuration',
      access_approvals:   'Approvals & Audit',
      access_approvals_d: 'Approve or reject quotes that trip approval rules',
      btn_save_config:    'Save Configuration',
      btn_revoke:         'Revoke All Access',
      // Settings
      page_settings:      'Settings',
      btn_save_changes:   'Save Changes',
      toast_saved:        'Settings saved successfully',
      sect_company:       'Company Information',
      lbl_co_name:        'Company Name',
      lbl_website:        'Website URL',
      lbl_co_email:       'Contact Email',
      lbl_co_phone:       'Phone Number',
      lbl_address:        'Head Office Address',
      sect_account:       'My Account',
      lbl_username:       'Admin Username',
      lbl_display_name:   'Your Name',
      lbl_your_email:     'Login Email',
      lbl_cur_pass:       'Current Password',
      lbl_new_pass:       'New Password',
      lbl_confirm_pass:   'Confirm New Password',
      btn_update_account: 'Update Account',
      acct_need_current:  'Enter your current password to change it.',
      acct_pw_short:      'New password must be at least 8 characters.',
      acct_pw_mismatch:   'New passwords do not match.',
      acct_wrong_current: 'Current password is incorrect.',
      acct_updated:       'Account updated successfully.',
      acct_failed:        'Could not update the account.',
      sect_notif:         'Notification Preferences',
      notif1_t:           'New Booking Request',
      notif1_d:           'Get notified when a new concrete booking is submitted',
      notif2_t:           'New Inbox Message',
      notif2_d:           'Get notified when a customer submits a contact form',
      notif3_t:           'New Customer Record',
      notif3_d:           'Alert when a new customer is added to the database',
      notif4_t:           'Weekly Summary Report',
      notif4_d:           'Receive a weekly digest of requests, leads, and volumes',
      sect_system:        'System Preferences',
      lbl_lang:           'Default Language',
      lbl_tz:             'Timezone',
      lbl_date_fmt:       'Date Format',
      lbl_vol_unit:       'Volume Unit',
      sect_danger:        'Danger Zone',
      danger_t:           'Clear All Booking Records',
      danger_d:           'Permanently delete all booking requests from the system. This cannot be undone.',
      btn_clear:          'Clear Records',
      // Login
      login_heading:      'ACCESS',
      login_sub:          'Authorized personnel only',
      lbl_username_l:     'Username / Email',
      lbl_password:       'Password',
      forgot_pw:          'Forgot password?',
      btn_login:          'LOGIN →',
      login_footer:       'Secure System Environment',
      // Placeholders
      ph_search:          'Search…',
      ph_search_req:      'Search requests…',
      ph_search_cust:     'Search customers…',
      ph_search_pers:     'Search personnel…',
      ph_username:        'Enter your username or email',
      ph_password:        'Enter your password',
      ph_reply:           'Write a reply…',
      ph_int_note:        'Add an internal note about this status change…',
      ph_notes:           'Add any delivery notes, conditions, or instructions…',
    },

    ar: {
      // Sidebar — Sales System
      nav_sales_system:   'نظام المبيعات',
      nav_sales_overview: 'نظرة عامة على المبيعات',
      nav_leads:          'العملاء المحتملون والفرص',
      nav_quotes_bookings:'عروض الأسعار وطلبات الحجز',
      nav_sales_forms:    'نماذج المبيعات',
      nav_calendar:       'إدارة التقويم',
      nav_tasks:          'المهام والمتابعات',
      nav_reports:        'التقارير والتحليلات',
      nav_approvals:      'الموافقات والتدقيق',
      // Shared sales vocabulary
      product_concrete:   'خرسانة',
      product_precast:    'مسبقة الصب',
      product_block:      'بلوك بناء',
      priority_high:      'عالية',
      priority_medium:    'متوسطة',
      priority_low:       'منخفضة',
      stage_new:          'جديد',
      stage_contacted:    'تم التواصل',
      stage_qualified:    'مؤهل',
      stage_quoted:       'تم التسعير',
      stage_negotiation:  'تفاوض',
      stage_won:          'تم الفوز',
      stage_lost:         'خسارة',
      src_walkin:         'زيارة شخصية',
      src_phone:          'هاتف',
      src_website:        'الموقع الإلكتروني',
      src_rep:            'مندوب مبيعات',
      lbl_follow_up:      'تاريخ المتابعة',
      lbl_priority:       'الأولوية',
      lbl_stage:          'المرحلة',
      lbl_product_type:   'نوع المنتج',
      lbl_source:         'مصدر العميل',
      lbl_rep:            'المندوب',
      status_booked:      'محجوز',
      status_paid:        'مدفوع',
      status_delayed:     'مؤجل',
      status_cancelled:   'ملغي',
      status_expired:     'منتهي الصلاحية',
      status_pending_conf:'بانتظار التأكيد',
      btn_add:            'إضافة',
      btn_save:           'حفظ',
      btn_cancel:         'إلغاء',
      btn_delete:         'حذف',
      btn_edit:           'تعديل',
      btn_close:          'إغلاق',
      // Leads page
      page_leads:         'إدارة العملاء المحتملين والفرص',
      btn_add_lead:       '← إضافة عميل محتمل',
      leads_all:          'الكل',
      lbl_name:           'الاسم',
      lbl_company:        'الشركة',
      lbl_notes:          'ملاحظات',
      th_waiting:         'مدة الانتظار',
      th_follow_up:       'المتابعة',
      th_product:         'المنتج',
      th_actions:         'إجراءات',
      leads_overdue_fu:   'متأخر',
      leads_dup_warn:     'تكرار محتمل — توجد سجلات مطابقة:',
      leads_none:         'لا يوجد عملاء محتملون بعد',
      leads_none_d:       'أضف أول عميل محتمل لبدء تتبع مسار المبيعات.',
      btn_convert:        'تحويل إلى عرض سعر',
      leads_converted:    'تم التحويل',
      modal_add_lead:     'إضافة عميل محتمل',
      modal_edit_lead:    'تعديل عميل محتمل',
      fu_required:        'يجب تحديد تاريخ المتابعة قبل الحفظ.',
      name_required:      'الاسم ورقم الهاتف مطلوبان.',
      toast_lead_saved:   'تم حفظ العميل المحتمل',
      toast_lead_deleted: 'تم حذف العميل المحتمل',
      toast_lead_converted:'تم تحويل العميل المحتمل إلى طلب عرض سعر',
      del_lead_t:         'حذف العميل المحتمل',
      del_lead_d:         'سيؤدي هذا إلى حذف العميل المحتمل نهائياً. لا يمكن التراجع عن هذا الإجراء.',
      ph_search_leads:    'البحث في العملاء المحتملين…',
      ph_rep_name:        'اسم المندوب…',
      ph_lead_notes:      'ملاحظات حول هذا العميل المحتمل…',
      // Sales Forms page
      page_sales_forms:   'نماذج المبيعات',
      sf_intro:           'أنشئ عرض سعر أو حجزاً نيابة عن العميل — للزيارات الشخصية أو الهاتف أو طلبات المندوبين.',
      sf_tab_concrete:    'حجز خرسانة',
      sf_tab_precast:     'عرض سعر مسبقة الصب',
      sf_tab_block:       'عرض سعر بلوك بناء',
      sf_client:          'اسم العميل',
      sf_location:        'موقع المشروع',
      sf_qty_m3:          'الكمية (م³)',
      sf_qty_units:       'الكمية (وحدة)',
      sf_qty_pcs:         'الكمية (قطعة)',
      sf_req_date:        'التاريخ المطلوب',
      sf_dispatch:        'الإطار الزمني للإرسال',
      sf_mix_grade:       'درجة الخلطة',
      sf_precast_product: 'منتج مسبق الصب',
      sf_block_product:   'منتج البلوك',
      sf_details:         'تفاصيل إضافية',
      sf_add_customer:    'إضافة هذا العميل إلى قاعدة بيانات العملاء',
      sf_existing_customer:'تمت مطابقة سجل عميل موجود — لن يتم إنشاء سجل مكرر.',
      sf_submit:          '← إنشاء وإرسال إلى سير العمل',
      sf_required_err:    'يرجى تعبئة جميع الحقول المطلوبة.',
      sf_success:         'تم الإنشاء بنجاح — الآن في عروض الأسعار وطلبات الحجز',
      sf_view_req:        '← عرض الطلبات',
      sf_approval_note:   'سيتطلب هذا الطلب موافقة:',
      apr_large_volume:   'حجز بكمية كبيرة',
      apr_high_discount:  'خصم أعلى من الحد المسموح',
      apr_same_day:       'إرسال عاجل في نفس اليوم',
      sf_dw_morning:      'صباحاً (06:00–10:00)',
      sf_dw_midday:       'منتصف اليوم (10:00–14:00)',
      sf_dw_afternoon:    'بعد الظهر (14:00–18:00)',
      sf_dw_evening:      'مساءً (18:00–22:00)',
      sf_dw_flexible:     'مرن',
      pc_hollow:          'بلاطات مجوفة',
      pc_wall:            'ألواح جدارية',
      pc_beam:            'كمرات وأعمدة',
      pc_stairs:          'سلالم',
      pc_boundary:        'أسوار حدودية',
      pc_custom:          'عنصر مخصص',
      bl_nh20:            'بلوك مفرغ عادي (20سم)',
      bl_ns20:            'بلوك مصمت عادي (20سم)',
      bl_ins20:           'بلوك معزول (20سم)',
      bl_ins30:           'بلوك معزول أزرق (30سم)',
      bl_wins30:          'بلوك معزول أبيض (30سم)',
      // Calendar page
      page_calendar:      'إدارة التقويم',
      cal_add_entry:      '← إضافة موعد',
      cal_export:         'تصدير',
      cal_export_day:     'اليوم (CSV)',
      cal_export_week:    'هذا الأسبوع (CSV)',
      cal_export_month:   'هذا الشهر (CSV)',
      cal_today:          'اليوم',
      cal_unassigned:     'قائمة غير المجدول',
      cal_unassigned_d:   'طلبات بدون تاريخ تسليم أو إطار زمني للإرسال.',
      cal_schedule:       'جدولة',
      cal_capacity:       'السعة اليومية',
      cal_conflict_window:'تعارض في الإطار الزمني للإرسال',
      cal_conflict_capacity:'تجاوز السعة اليومية',
      cal_tentative:      'مبدئي',
      cal_upcoming:       'القادم (خلال 3 أيام)',
      cal_none_upcoming:  'لا توجد مواعيد خلال الأيام الثلاثة القادمة.',
      cal_entry:          'موعد في التقويم',
      cal_day:            'اليوم',
      cal_qty:            'الكمية',
      cal_mark_tentative: 'حجز مبدئي (حجز مساحة قبل التأكيد)',
      cal_filter_region:  'تصفية حسب الموقع…',
      cal_filter_rep:     'تصفية حسب المندوب…',
      cal_empty_day:      'لا توجد مواعيد',
      toast_entry_saved:  'تم حفظ الموعد',
      toast_entry_deleted:'تم حذف الموعد',
      toast_rescheduled:  'تمت إعادة الجدولة',
      cal_linked_req:     'الطلب المرتبط',
      // Customer profile
      cust_profile:       'ملف العميل',
      cust_timeline:      'سجل النشاط',
      cust_key:           'عميل رئيسي',
      cust_mark_key:      'تحديد كعميل رئيسي (عميل متكرر مهم)',
      lbl_segment:        'الفئة',
      seg_none:           '— بدون —',
      seg_contractor:     'مقاول',
      seg_consultant:     'استشاري',
      seg_walkin:         'زيارة شخصية',
      seg_government:     'جهة حكومية',
      seg_retail:         'تجزئة',
      seg_developer:      'مطوّر عقاري',
      cust_stats:         'سجل المبيعات',
      cust_quotes_n:      'عروض الأسعار',
      cust_booked_n:      'محجوز / مدفوع',
      cust_volume_n:      'إجمالي الكمية',
      cust_no_timeline:   'لا يوجد نشاط مسجل بعد.',
      toast_cust_saved:   'تم حفظ العميل',
      flt_all_segments:   'كل الفئات',
      // Tasks page
      page_tasks:         'المهام والمتابعات',
      btn_add_task:       '← إضافة مهمة',
      task_all:           'الكل',
      task_open:          'مفتوحة',
      task_overdue:       'متأخرة',
      task_done:          'منجزة',
      task_title:         'المهمة',
      task_due:           'تاريخ الاستحقاق',
      task_assignee:      'مسندة إلى',
      task_link:          'السجل المرتبط',
      task_link_none:     '— غير مرتبطة —',
      task_link_request:  'عرض سعر / حجز',
      task_link_lead:     'عميل محتمل',
      task_link_customer: 'عميل',
      task_none:          'لا توجد مهام بعد',
      task_none_d:        'أنشئ مهام متابعة حتى لا يفوتك أي شيء.',
      task_mark_done:     'إنجاز',
      task_reopen:        'إعادة فتح',
      modal_add_task:     'إضافة مهمة',
      modal_edit_task:    'تعديل مهمة',
      task_title_req:     'عنوان المهمة وتاريخ الاستحقاق مطلوبان.',
      toast_task_saved:   'تم حفظ المهمة',
      toast_task_deleted: 'تم حذف المهمة',
      ph_task_title:      'مثال: الاتصال بالعميل بخصوص عرض C35…',
      ph_search_tasks:    'البحث في المهام…',
      // Sales Overview additions
      ov_pipeline:        'مسار العملاء المحتملين',
      ov_followups:       'المتابعات المتأخرة',
      ov_upcoming:        'التسليمات القادمة (7 أيام)',
      ov_open_leads:      'عملاء محتملون نشطون',
      ov_pending_q:       'عروض أسعار معلقة',
      ov_upcoming_b:      'حجوزات قادمة',
      ov_overdue_f:       'متابعات متأخرة',
      ov_pending_apr:     'موافقات معلقة',
      kpi_hint_pending:   'طلبات معلقة',
      kpi_hint_awaiting:  'بانتظار العميل',
      ov_no_leads:        'لا يوجد عملاء محتملون في المسار بعد — أضف واحداً من صفحة العملاء المحتملين والفرص.',
      ov_no_overdue:      'لا توجد متابعات متأخرة — عمل رائع في متابعة كل شيء!',
      ov_no_upcoming:     'لا توجد تسليمات مجدولة خلال الأيام السبعة القادمة.',
      // Reports page
      page_reports:       'تقارير وتحليلات المبيعات',
      rpt_category:       'أداء الفئات',
      rpt_requests:       'الطلبات',
      rpt_quoted_value:   'قيمة العروض (ر.س)',
      rpt_booked:         'محجوز / مدفوع',
      rpt_volume:         'الكمية',
      rpt_funnel:         'تحويل مسار المبيعات',
      rpt_f_inquiries:    'الاستفسارات',
      rpt_f_quoted:       'تم التسعير',
      rpt_f_confirmed:    'مؤكد (محجوز / مدفوع)',
      rpt_f_closed:       'مغلق / تم التسليم',
      rpt_conv_rate:      'معدل تحويل عروض الأسعار',
      rpt_conv_d:         'العروض التي تحولت إلى أعمال مؤكدة',
      rpt_reps:           'أداء المندوبين',
      rpt_rep_leads:      'عملاء محتملون',
      rpt_rep_requests:   'طلبات',
      rpt_rep_won:        'مكتمل / محجوز',
      rpt_rep_conv:       'نسبة التحويل',
      rpt_no_reps:        'لا توجد سجلات من مندوبين بعد.',
      rpt_customers:      'تحليلات العملاء',
      rpt_top_customers:  'أفضل العملاء',
      rpt_repeat:         'عملاء متكررون',
      rpt_keys:           'عملاء رئيسيون',
      rpt_no_cust:        'لا يوجد نشاط عملاء بعد.',
      rpt_ops:            'مؤشرات تشغيلية',
      rpt_delayed:        'أعمال مؤجلة',
      rpt_expired:        'عروض منتهية',
      rpt_load7:          'حمل الحجوزات لـ7 أيام (م³)',
      rpt_fu_compliance:  'الالتزام بالمتابعة',
      rpt_total:          'الإجمالي',
      rpt_export_csv:     'تصدير CSV',
      rpt_print:          'طباعة / PDF',
      // ── Plant Operations ──
      nav_ops_system:     'عمليات المصنع',
      nav_ops_board:      'لوحة العمليات',
      nav_ops_orders:     'الطلبات من المبيعات',
      nav_ops_fleet:      'الأسطول والبيانات الرئيسية',
      nav_ops_reports:    'تقارير العمليات',
      access_operations:  'عمليات المصنع',
      access_operations_d:'لوحة الإرسال واستلام الطلبات والأسطول وتقارير العمليات',
      // ops statuses
      ops_booked:         'محجوز',
      ops_authorized:     'مصرح به',
      ops_on_hold:        'معلق',
      ops_scheduled:      'مجدول',
      ops_batching:       'جارٍ الخلط',
      ops_loading:        'جارٍ التحميل',
      ops_en_route:       'في الطريق',
      ops_on_site:        'في الموقع',
      ops_discharging:    'جارٍ التفريغ',
      ops_washout:        'غسيل',
      ops_returned:       'عاد للمصنع',
      ops_completed:      'مكتمل',
      ops_delayed:        'متأخر',
      ops_pending_review: 'قيد المراجعة',
      // delay reasons
      dly_traffic:        'ازدحام مروري',
      dly_plant:          'عطل في المصنع',
      dly_pump:           'عطل في المضخة',
      dly_truck:          'عطل في الشاحنة',
      dly_site:           'الموقع غير جاهز',
      dly_weather:        'أحوال جوية',
      dly_quality:        'مشكلة جودة',
      dly_customer:       'تأخير من العميل',
      dly_other:          'أخرى',
      // reject reasons
      rej_slump:          'هبوط خارج المواصفات',
      rej_wait:           'انتظار زائد',
      rej_mix:            'خلطة خاطئة',
      rej_site:           'رفض من الموقع',
      rej_other:          'أخرى',
      // shifts
      shift_morning:      'صباحية',
      shift_evening:      'مسائية',
      shift_night:        'ليلية',
      // orders page
      page_ops_orders:    'الطلبات من المبيعات',
      oo_intro:           'حجوزات الخرسانة المتزامنة من نظام المبيعات. المبيعات تملك البيانات التجارية — والعمليات تضيف تفاصيل التنفيذ فقط.',
      oo_sync:            'مزامنة من المبيعات',
      oo_synced_n:        'طلب جديد تمت مزامنته',
      oo_none:            'لا توجد طلبات تشغيلية بعد',
      oo_none_d:          'حجوزات الخرسانة المؤكدة من نظام المبيعات ستظهر هنا تلقائياً.',
      oo_commercial:      'تجاري (من المبيعات — للقراءة فقط)',
      oo_execution:       'التنفيذ (العمليات)',
      oo_auth_status:     'التصريح',
      oo_site_ready:      'تم تأكيد جاهزية الموقع (مطلوب قبل الإرسال)',
      oo_plant:           'المصنع',
      oo_no_plant:        '— لم يُعيَّن مصنع —',
      oo_priority:        'أولوية العمل',
      pri_urgent:         'عاجل',
      pri_high:           'عالية',
      pri_normal:         'عادية',
      pri_low:            'منخفضة',
      oo_notes:           'ملاحظات تشغيلية',
      oo_mark_complete:   'إكمال العمل',
      oo_completed_note:  'يتم مشاركة الإكمال مع نظام المبيعات (المرحلة: تم التسليم).',
      oo_trips:           'رحلات',
      oo_view_board:      '← فتح في اللوحة',
      toast_oo_saved:     'تم تحديث الطلب',
      toast_oo_completed: 'اكتمل العمل — تم تحديث المبيعات إلى تم التسليم',
      // board page
      page_ops_board:     'لوحة العمليات',
      ob_today:           'اليوم',
      ob_capacity:        'السعة اليومية',
      ob_alerts:          'تنبيهات الاستثناءات',
      ob_no_alerts:       'لا توجد استثناءات — العمليات تسير بسلاسة.',
      ob_unscheduled:     'مصرح به — بانتظار الرحلات',
      ob_no_orders:       'لا يوجد شيء مجدول لهذا اليوم.',
      ob_add_trip:        'إضافة رحلة',
      ob_trip:            'رحلة',
      ob_truck:           'شاحنة خلاطة',
      ob_pump:            'المضخة',
      ob_no_pump:         '— بدون مضخة —',
      ob_driver:          'السائق',
      ob_load_time:       'وقت التحميل',
      ob_qty:             'الحمولة (م³)',
      ob_advance:         'المرحلة التالية',
      ob_mark_delay:      'تسجيل تأخير',
      ob_delay_reason:    'سبب التأخير',
      ob_reject_load:     'رفض الحمولة',
      ob_reject_reason:   'سبب الرفض',
      ob_busy_warn:       'هذا الأصل معيّن بالفعل لرحلة نشطة أخرى في هذا اليوم.',
      ob_trip_done:       'اكتملت الرحلة',
      ob_alert_delay:     'متأخر',
      ob_alert_overcap:   'تجاوز السعة',
      ob_alert_conflict:  'تعارض في الأصول',
      ob_alert_pending:   'بانتظار التصريح مع تسليم اليوم',
      toast_trip_saved:   'تم حفظ الرحلة',
      toast_trip_deleted: 'تم حذف الرحلة',
      // fleet page
      page_ops_fleet:     'الأسطول والبيانات الرئيسية',
      fl_plants:          'المصانع',
      fl_mixers:          'الشاحنات الخلاطة',
      fl_pumps:           'شاحنات الضخ',
      fl_staff:           'موظفو المصنع',
      fl_add:             '← إضافة',
      fl_name:            'الاسم / المعرف',
      fl_capacity:        'السعة',
      fl_boom:            'الذراع (م)',
      fl_operator:        'المشغل / السائق',
      fl_role:            'الدور',
      fl_shift:           'الوردية',
      fl_status:          'الحالة',
      ast_available:      'متاح',
      ast_on_trip:        'في رحلة',
      ast_maintenance:    'صيانة',
      fl_trips_today:     'رحلات اليوم',
      fl_none:            'لا يوجد شيء هنا بعد — أضف أول سجل.',
      fl_del_t:           'حذف السجل',
      fl_del_d:           'سيؤدي هذا إلى حذف السجل نهائياً. لا يمكن التراجع.',
      toast_ast_saved:    'تم حفظ السجل',
      toast_ast_deleted:  'تم حذف السجل',
      role_dispatcher:    'منسق إرسال',
      role_supervisor:    'مشرف مصنع',
      role_operator:      'مشغل مصنع',
      role_driver:        'سائق',
      role_pump_op:       'مشغل مضخة',
      role_fleet:         'منسق أسطول',
      // ops reports
      page_ops_reports:   'تقارير وتحليلات العمليات',
      or_production:      'الإنتاج — المخطط مقابل الفعلي (7 أيام)',
      or_planned:         'المخطط',
      or_actual:          'تم التسليم',
      or_ontime:          'الإرسال في الوقت المحدد',
      or_ontime_d:        'الرحلات المحملة ضمن نافذتها المخططة',
      or_turnaround:      'متوسط دورة الشاحنة',
      or_mins:            'دقيقة',
      or_truck_util:      'استخدام الخلاطات',
      or_pump_util:       'استخدام المضخات',
      or_delays:          'التأخيرات حسب السبب',
      or_no_delays:       'لا توجد تأخيرات مسجلة.',
      or_rejected:        'الحمولات المرفوضة',
      or_clients:         'أداء خدمة العملاء',
      or_client:          'العميل',
      or_jobs:            'الأعمال',
      or_volume:          'تم التسليم (م³)',
      or_trips:           'الرحلات',
      or_delays_n:        'التأخيرات',
      or_no_data:         'لا توجد بيانات تشغيلية بعد.',
      // ── Precast Operations ──
      nav_pc_system:      'عمليات مسبقة الصب',
      nav_pc_orders:      'طلبات مسبقة الصب',
      nav_pc_production:  'قائمة الإنتاج',
      nav_pc_delivery:    'تخطيط التسليم',
      nav_pc_reports:     'تقارير مسبقة الصب',
      access_precast:     'عمليات مسبقة الصب',
      access_precast_d:   'طلبات مسبقة الصب وقائمة الإنتاج وتخطيط التسليم والتقارير',
      fl_molds:           'القوالب وخطوط الإنتاج',
      fl_trailers:        'المقطورات',
      // precast statuses
      pc_design_review:   'مراجعة التصميم',
      pc_queued:          'في القائمة',
      pc_mold_prep:       'تجهيز القالب',
      pc_casting:         'جارٍ الصب',
      pc_curing:          'معالجة',
      pc_demolding:       'فك القالب',
      pc_qc:              'فحص الجودة',
      pc_in_yard:         'في الساحة',
      pc_in_production:   'قيد الإنتاج',
      pc_ready_yard:      'جاهز في الساحة',
      pc_delivering:      'جارٍ التسليم',
      pc_planned:         'مخطط',
      pc_delivered:       'تم التسليم',
      // QC reasons
      qc_surface:         'عيب سطحي',
      qc_dimension:       'خطأ في الأبعاد',
      qc_crack:           'تشققات',
      qc_rebar:           'مشكلة في التسليح',
      qc_curing:          'مشكلة في المعالجة',
      qc_other:           'أخرى',
      // design
      ds_awaiting:        'بانتظار المخططات',
      ds_approved:        'تمت الموافقة على التصميم',
      po_design:          'حالة التصميم',
      // orders page
      page_pc_orders:     'طلبات مسبقة الصب',
      po_intro:           'طلبات مسبقة الصب المتزامنة من نظام المبيعات. المبيعات تملك البيانات التجارية — وعمليات مسبقة الصب تضيف التصميم والإنتاج وتنفيذ التسليم.',
      po_none:            'لا توجد طلبات مسبقة الصب بعد',
      po_none_d:          'عروض مسبقة الصب المؤكدة من نظام المبيعات ستظهر هنا تلقائياً.',
      po_units:           'وحدة',
      po_castings:        'عمليات صب',
      po_deliveries:      'تسليمات',
      po_open_production: '← فتح الإنتاج',
      po_open_delivery:   '← فتح التسليم',
      po_yard:            'في الساحة',
      po_delivered_n:     'تم التسليم',
      toast_po_saved:     'تم تحديث الطلب',
      toast_po_completed: 'اكتمل العمل — تم تحديث المبيعات إلى تم التسليم',
      // production page
      page_pc_production: 'قائمة الإنتاج',
      pp_line_capacity:   'سعة الخطوط',
      pp_no_lines:        'لا توجد خطوط إنتاج بعد — أضف القوالب والخطوط في الأسطول والبيانات الرئيسية.',
      pp_add_casting:     'إضافة صبّة',
      pp_line:            'الخط / القالب',
      pp_element:         'العنصر',
      pp_units:           'الوحدات',
      pp_cast_day:        'يوم الصب',
      pp_qc_pass:         'اجتياز الفحص',
      pp_qc_fail:         'فشل الفحص',
      pp_qc_reason:       'سبب فشل فحص الجودة',
      pp_no_orders:       'لا توجد طلبات مسبقة الصب مصرح بها قيد الإنتاج.',
      pp_awaiting_design: 'بانتظار الموافقة على التصميم',
      pp_over_line:       'تجاوز سعة الخط',
      pp_alert_qc:        'فشل في فحص الجودة',
      toast_cast_saved:   'تم حفظ الصبّة',
      toast_cast_deleted: 'تم حذف الصبّة',
      // delivery page
      page_pc_delivery:   'تخطيط التسليم',
      pd_add:             'إضافة تسليم',
      pd_trailer:         'المقطورة',
      pd_no_trailer:      '— بدون مقطورة —',
      pd_items:           'قائمة الحمولة',
      pd_day:             'يوم التسليم',
      pd_none:            'لا توجد تسليمات مخططة.',
      pd_yard_ready:      'جاهز في الساحة',
      pd_yard_short:      'الوحدات في الساحة أقل من هذه الحمولة',
      pd_alert_delay:     'تأخر التسليم',
      toast_del_saved:    'تم حفظ التسليم',
      toast_del_deleted:  'تم حذف التسليم',
      // reports page
      page_pc_reports:    'تقارير وتحليلات مسبقة الصب',
      pr_output:          'إنتاجية الإنتاج — المصبوب مقابل المسلَّم (7 أيام)',
      pr_cast:            'مصبوب',
      pr_delivered:       'تم التسليم',
      pr_qc_rate:         'نسبة اجتياز فحص الجودة',
      pr_qc_d:            'الصبّات التي اجتازت مراقبة الجودة',
      pr_ontime:          'التسليم في الوقت المحدد',
      pr_line_util:       'استخدام الخطوط',
      pr_trailer_util:    'استخدام المقطورات',
      pr_qc_fails:        'إخفاقات فحص الجودة حسب السبب',
      pr_no_qc:           'لا توجد إخفاقات فحص جودة مسجلة.',
      pr_elements:        'الإنتاج حسب العنصر',
      pr_element:         'العنصر',
      pr_orders_n:        'الطلبات',
      // Approvals & Audit page
      page_approvals:     'نظام الموافقات والتدقيق',
      apr_queue:          'الموافقات المعلقة',
      apr_queue_d:        'عروض الأسعار والحجوزات بانتظار قرار المسؤول.',
      apr_none:           'لا يوجد شيء بانتظار الموافقة.',
      apr_approve:        'موافقة',
      apr_reject:         'رفض',
      apr_note_ph:        'ملاحظة اختيارية لهذا القرار…',
      apr_approved_toast: 'تمت الموافقة — تم إرسال بريد عرض السعر للعميل.',
      apr_approved_noemail:'تمت الموافقة. لا يوجد بريد إلكتروني للعميل، لذا لم يُرسل شيء.',
      apr_rejected_toast: 'تم الرفض — أُعيد الطلب إلى حالة معلّق.',
      apr_capacity:       'سعة الخرسانة — الأيام السبعة القادمة',
      apr_capacity_d:     'الكمية المحجوزة يومياً مقابل سعة 600 م³. الأيام المتجاوزة تبقى مسموحة لكنها تُعلَّم للتجاوز اليدوي.',
      apr_audit:          'سجل التدقيق',
      apr_audit_d:        'تعديلات العروض وتغييرات الحالة والموافقات وإجراءات مهمة أخرى.',
      apr_no_audit:       'لا توجد سجلات تدقيق بعد.',
      th_action:          'الإجراء',
      th_detail:          'التفاصيل',
      th_by:              'بواسطة',
      ph_search_audit:    'البحث في سجل التدقيق…',
      apr_reasons:        'الأسباب',
      // Sidebar
      nav_overview:       'نظرة عامة',
      nav_bookings:       'عروض الأسعار وطلبات الحجز',
      nav_inbox:          'صندوق الوارد',
      nav_profile:        'ملف تعريف الشركة',
      nav_upload_profile: 'رفع PDF',
      profile_no_upload:  'لم يتم رفع ملف بعد',
      profile_updated:    'تم تحديث ملف الشركة بنجاح!',
      nav_customers:      'قاعدة بيانات العملاء',
      nav_access:         'صلاحيات المستخدمين',
      nav_settings:       'الإعدادات',
      nav_role:           'مدير النظام',
      nav_back:           'العودة للموقع',
      nav_logout:         'تسجيل الخروج',
      // Overview
      page_overview:      'نظرة عامة على المبيعات',
      kpi_requests:       'إجمالي الطلبات',
      kpi_leads:          'عملاء جدد',
      kpi_volume:         'الحجم التقديري (م³)',
      kpi_quotes:         'عروض الأسعار النشطة',
      recent_title:       'طلبات عروض الأسعار الأخيرة',
      recent_view_all:    '← عرض الكل',
      th_client_name:     'اسم العميل',
      th_date:            'تاريخ التقديم',
      th_qty_m3:          'الكمية (م³)',
      th_status:          'الحالة',
      // Status badges
      status_pending_r:   'قيد المراجعة',
      status_pending:     'معلّق',
      status_quote_sent:  'تم إرسال العرض',
      status_approved:    'موافق عليه',
      status_contacted:   'تم التواصل',
      status_rejected:    'مرفوض',
      // Bookings
      page_bookings:      'عروض الأسعار وطلبات الحجز',
      btn_filter:         'تصفية',
      filter_by_status:   'تصفية حسب الحالة',
      filter_all:         'جميع الطلبات',
      filter_clear:       'مسح التصفية',
      label_quantity:     'الكمية',
      label_mix:          'نوع الخلطة',
      label_location:     'الموقع',
      label_client_msg:   'رسالة العميل',
      label_client:       'العميل',
      btn_gen_quote:      '← إنشاء عرض سعر',
      btn_upd_status:     'تحديث الحالة',
      // Quote modal
      modal_gen_quote:    'إنشاء عرض سعر',
      modal_client:       'العميل',
      modal_qty:          'الكمية',
      modal_mix:          'نوع الخلطة',
      modal_price:        'السعر لكل م³ (ر.س)',
      modal_total:        'الإجمالي (ر.س)',
      modal_delivery:     'تاريخ التسليم',
      modal_notes:        'ملاحظات للعميل',
      modal_cancel:       'إلغاء',
      modal_send_quote:   'إرسال العرض',
      toast_quote_sent:   'تم إرسال عرض السعر بنجاح!',
      modal_discount:     'الخصم (٪)',
      modal_expiry:       'انتهاء صلاحية العرض',
      modal_reason:       'سبب التعديل',
      ph_reason:          'ما سبب تعديل عرض السعر؟',
      apr_submitted:      'تم حفظ العرض وإرساله للموافقة. سيُرسل البريد الإلكتروني للعميل بعد الموافقة.',
      err_past_date:      'لا يمكن اختيار تاريخ في الماضي — لا يمكن حجز الخرسانة ليوم انتهى بالفعل.',
      apr_pending_banner: 'بانتظار الموافقة — تم تعليق إرسال البريد للعميل.',
      apr_rejected_banner:'تم رفض الموافقة.',
      exp_expires:        'ينتهي في',
      flt_all_products:   'كل المنتجات',
      // Status modal
      modal_upd_status:   'تحديث الحالة',
      modal_new_status:   'الحالة الجديدة',
      modal_int_note:     'ملاحظة داخلية (اختياري)',
      modal_save_status:  'حفظ الحالة',
      toast_status_saved: 'تم تحديث الحالة بنجاح!',
      // Inbox
      page_inbox:         'صندوق الوارد',
      tab_all:            'الكل',
      tab_unread:         'غير مقروء',
      tab_flagged:        'مميّز',
      btn_send_reply:     'إرسال الرد',
      // Customers
      page_customers:     'قاعدة بيانات العملاء',
      btn_export:         'تصدير CSV',
      btn_add_record:     '← إضافة سجل',
      btn_sort:           'ترتيب',
      th_cust_name:       'اسم العميل',
      th_email:           'البريد الإلكتروني',
      th_phone:           'الهاتف',
      th_last_activity:   'آخر نشاط',
      th_location_c:      'الموقع',
      action_view:        '← عرض التفاصيل',
      pagination_cust:    'عرض 1 إلى 4 من أصل 97 نتيجة',
      // Access
      page_access:        'إدارة الصلاحيات',
      btn_add_user:       '← إضافة مستخدم',
      active_personnel:   'الموظفون النشطون',
      th_name:            'الاسم',
      th_role_a:          'الدور',
      th_status_a:        'الحالة',
      status_active:      'نشط',
      status_inactive:    'غير نشط',
      action_manage:      'إدارة',
      pagination_access:  'عرض 1 إلى 3 من أصل 12 موظفاً',
      module_access:      'التحكم في صلاحيات الوحدات',
      access_bookings:    'طلبات عروض الأسعار',
      access_bookings_d:  'عرض وإدارة الحجوزات',
      access_financials:  'الشؤون المالية',
      access_fin_d:       'الوصول إلى التقارير المالية',
      access_customers:   'بيانات العملاء',
      access_cust_d:      'عرض قاعدة بيانات العملاء',
      access_settings:    'إعدادات النظام',
      access_sett_d:      'تعديل إعدادات النظام',
      access_approvals:   'الموافقات والتدقيق',
      access_approvals_d: 'الموافقة على العروض الخاضعة لقواعد الموافقة أو رفضها',
      btn_save_config:    'حفظ الإعدادات',
      btn_revoke:         'إلغاء جميع الصلاحيات',
      // Settings
      page_settings:      'الإعدادات',
      btn_save_changes:   'حفظ التغييرات',
      toast_saved:        'تم حفظ الإعدادات بنجاح',
      sect_company:       'معلومات الشركة',
      lbl_co_name:        'اسم الشركة',
      lbl_website:        'رابط الموقع',
      lbl_co_email:       'البريد الإلكتروني',
      lbl_co_phone:       'رقم الهاتف',
      lbl_address:        'عنوان المقر الرئيسي',
      sect_account:       'حسابي',
      lbl_username:       'اسم المستخدم',
      lbl_display_name:   'اسمك',
      lbl_your_email:     'بريد تسجيل الدخول',
      lbl_cur_pass:       'كلمة المرور الحالية',
      lbl_new_pass:       'كلمة المرور الجديدة',
      lbl_confirm_pass:   'تأكيد كلمة المرور الجديدة',
      btn_update_account: 'تحديث الحساب',
      acct_need_current:  'أدخل كلمة المرور الحالية لتغييرها.',
      acct_pw_short:      'يجب ألا تقل كلمة المرور الجديدة عن 8 أحرف.',
      acct_pw_mismatch:   'كلمتا المرور الجديدتان غير متطابقتين.',
      acct_wrong_current: 'كلمة المرور الحالية غير صحيحة.',
      acct_updated:       'تم تحديث الحساب بنجاح.',
      acct_failed:        'تعذر تحديث الحساب.',
      sect_notif:         'تفضيلات الإشعارات',
      notif1_t:           'طلب حجز جديد',
      notif1_d:           'تلقّي إشعار عند تقديم طلب حجز خرسانة جديد',
      notif2_t:           'رسالة واردة جديدة',
      notif2_d:           'تلقّي إشعار عند إرسال العميل نموذج تواصل',
      notif3_t:           'سجل عميل جديد',
      notif3_d:           'تنبيه عند إضافة عميل جديد إلى قاعدة البيانات',
      notif4_t:           'تقرير ملخص أسبوعي',
      notif4_d:           'استلام ملخص أسبوعي للطلبات والعملاء والكميات',
      sect_system:        'تفضيلات النظام',
      lbl_lang:           'اللغة الافتراضية',
      lbl_tz:             'المنطقة الزمنية',
      lbl_date_fmt:       'تنسيق التاريخ',
      lbl_vol_unit:       'وحدة الحجم',
      sect_danger:        'منطقة الخطر',
      danger_t:           'مسح جميع سجلات الحجز',
      danger_d:           'حذف جميع طلبات الحجز نهائياً من النظام. لا يمكن التراجع عن هذا الإجراء.',
      btn_clear:          'مسح السجلات',
      // Login
      login_heading:      'دخول',
      login_sub:          'للموظفين المصرح لهم فقط',
      lbl_username_l:     'اسم المستخدم / البريد الإلكتروني',
      lbl_password:       'كلمة المرور',
      forgot_pw:          'نسيت كلمة المرور؟',
      btn_login:          '← تسجيل الدخول',
      login_footer:       'بيئة نظام آمنة',
      // Placeholders
      ph_search:          'بحث…',
      ph_search_req:      'البحث في الطلبات…',
      ph_search_cust:     'البحث في العملاء…',
      ph_search_pers:     'البحث في الموظفين…',
      ph_username:        'أدخل اسم المستخدم أو البريد الإلكتروني',
      ph_password:        'أدخل كلمة المرور',
      ph_reply:           'اكتب ردك…',
      ph_int_note:        'أضف ملاحظة داخلية حول تغيير الحالة…',
      ph_notes:           'أضف ملاحظات التسليم أو الشروط أو التعليمات…',
    }
  };

  // RTL CSS injected when Arabic is active
  var RTL_CSS = [
    'html[dir=rtl] body, html[dir=rtl] p, html[dir=rtl] span:not(.material-symbols-outlined),',
    'html[dir=rtl] a, html[dir=rtl] button, html[dir=rtl] label,',
    'html[dir=rtl] input, html[dir=rtl] textarea, html[dir=rtl] select,',
    'html[dir=rtl] td, html[dir=rtl] th { font-family: "Tajawal", Arial, sans-serif !important; }',
    'html[dir=rtl] h1, html[dir=rtl] h2, html[dir=rtl] h3,',
    'html[dir=rtl] h4, html[dir=rtl] h5 {',
    '  font-family: "Tajawal", Arial, sans-serif !important;',
    '  letter-spacing: 0 !important; }',
    'html[dir=rtl] .tracking-wide,',
    'html[dir=rtl] .tracking-widest { letter-spacing: 0 !important; }',
    /* Sidebar border — sidebar moves to the right in RTL, so the inner border flips */
    'html[dir=rtl] aside { border-right: 0 !important; border-left: 1px solid #DCDBD7 !important; }',
    /* Inbox message list pane */
    'html[dir=rtl] .rtl-border-flip { border-right: 0 !important; border-left: 1px solid #DCDBD7 !important; }',
    /* Booking card detail pane (border-l) */
    'html[dir=rtl] .rtl-border-iflip { border-left: 0 !important; border-right: 1px solid #DCDBD7 !important; }',
    /* Table text */
    'html[dir=rtl] th.text-left, html[dir=rtl] td.text-left { text-align: right; }',
    'html[dir=rtl] .text-right { text-align: left; }',
    /* Icon search field — mirror padding */
    'html[dir=rtl] .rtl-search { padding-left: 1rem !important; padding-right: 2.5rem !important; }',
    'html[dir=rtl] .rtl-icon-r { left: auto !important; right: 0.75rem !important; }',
  ].join('\n');

  var currentLang = localStorage.getItem('dashLang') || 'en';

  function applyDashLang(lang) {
    currentLang = lang;
    localStorage.setItem('dashLang', lang);
    var t = T[lang];
    var isAr = lang === 'ar';

    // Set html attributes
    document.documentElement.lang = lang;
    document.documentElement.dir = isAr ? 'rtl' : 'ltr';

    // Inject / clear RTL stylesheet
    var styleEl = document.getElementById('dash-rtl-css');
    if (isAr) {
      if (!styleEl) {
        styleEl = document.createElement('style');
        styleEl.id = 'dash-rtl-css';
        document.head.appendChild(styleEl);
      }
      styleEl.textContent = RTL_CSS;
    } else {
      if (styleEl) styleEl.textContent = '';
    }

    // Translate text content
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (t[key] !== undefined) el.textContent = t[key];
    });

    // Translate placeholders
    document.querySelectorAll('[data-i18n-ph]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-ph');
      if (t[key] !== undefined) el.placeholder = t[key];
    });

    // Update toggle button label
    var btn = document.getElementById('dash-lang-btn');
    if (btn) btn.textContent = isAr ? 'English' : 'عربي';
  }

  window.toggleDashLang = function () {
    applyDashLang(currentLang === 'en' ? 'ar' : 'en');
  };

  // Dictionary lookup for JS-composed strings (toasts, dynamic labels).
  window.dashT = function (key, fallback) {
    var t = T[currentLang] || {};
    return t[key] !== undefined ? t[key] : (fallback !== undefined ? fallback : key);
  };

  // Re-apply the CURRENT language to the whole document. Call this
  // after dynamically injecting new [data-i18n] nodes so they translate.
  window.reapplyDashLang = function () { applyDashLang(currentLang); };

  // Auto-apply on page load
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { applyDashLang(currentLang); });
  } else {
    applyDashLang(currentLang);
  }

}());
